### ISSUE TITLE
使用gradle命令打多渠道包的时候在最后一步碰到Execution failed for task ':app:assembleOfficialReleaseV2SignatureSchemeChannel'.

### ISSUE THREAD

**Issue by peerless2012** [Meituan-Dianping/walle#10]
错误信息

    * What went wrong:
    Execution failed for task ':app:assembleOfficialReleaseV2SignatureSchemeChannel'.
    > Cannot access first() element from an empty array

使用的命令是`gradle assembleOfficialRelease -PchannelFile=channel`,如果去掉后面渠道的参数是可以打包成功的。

**Comment by GavinCT** [comment]
提供下你的channel文件 路径是否放置正确？ 
channelfile是配置channel的文件

**Comment by peerless2012** [comment]
找到问题了，是channel配置文件格式问题，出问题的格式是

    # Google Play
    # googleplay
    # 百度
    baidu
    #
    # 360
    360cn
    #
    # 应用宝
    myapp

不过配置文件很多都是这样写，希望能适配一下，最后感谢分享 __walle__,不胜感激 @achellies

**Comment by GavinCT** [comment]
1.0.2已发，fix
尝试下

**Comment by peerless2012** [comment]
还是不行，附channel配置

    # Test
    #
    baidu # 百度
    360cn # 360
    myapp # 应用宝

**Comment by GavinCT** [comment]
![image](https://cloud.githubusercontent.com/assets/4016698/22095780/7a42836a-de52-11e6-861c-93e9586827a2.png)

你使用了1.0.2的plugin？  我这里一切正常啊
你报什么错？

**Comment by peerless2012** [comment]
Ok了，刚Project的插件没更新成1.0.2。
