### ISSUE TITLE
加固后重新签名渠道后，运行黑屏打不开应用

### ISSUE THREAD

**Issue by Ruijiao** [Meituan-Dianping/walle#100]
问题：
加固后重新签名并使用walle渠道化，但是运行的时候一直黑屏打不开应用了
步骤：
cmd命令：python channel.py yingyongbao
-----------------python文件-------------------------：
#coding=utf-8

import zipfile
import shutil
import os
import sys

if __name__ == '__main__':

    #序列化
    #windows
    os.system('zipalign_batch.bat '+sys.argv[1])
    
    #签名
    #windows
    os.system('E:/softWhare/android_studio_sdk/build-tools/25.0.0/apksigner sign --ks test.jks --ks-pass pass:1234567890 ./zipaligned/'+sys.argv[1]+'.apk')
    #渠道化
    if os.path.exists('./release'):
        shutil.rmtree('./release')
    os.mkdir('./release')
    os.system('java -jar walle-cli-all.jar batch -f channel'+' ./zipaligned/'+sys.argv[1]+'.apk ./release/')

------------------------zipalign_batch.bat文件------------------------------------
@echo off
echo begin running
if exist .\zipaligned (
	rd /s /q .\zipaligned
)
md .\zipaligned

E:\softWhare\android_studio_sdk\build-tools\25.0.0\zipalign -v 4  .\%1.apk .\zipaligned\%1.apk

echo end running

**Comment by GavinCT** [comment]
请先确认执行walle前的产物是否可以正常运行

**Comment by Ruijiao** [comment]
应该是签名错误，麻烦问下：apksigner 怎么设置别名以及密码呢

**Comment by GavinCT** [comment]
apksigner 直接回车 会有帮助

**Comment by Ruijiao** [comment]
没有设置密码和别名的方法
USAGE: apksigner <command> [options]
       apksigner --version
       apksigner --help

EXAMPLE:
       apksigner sign --ks release.jks app.apk
       apksigner verify --verbose app.apk

apksigner is a tool for signing Android APK files and for checking whether
signatures of APK files will verify on Android devices.


        COMMANDS

sign                  Sign the provided APK

verify                Check whether the provided APK is expected to verify on
                      Android

version               Show this tool's version number and exit

help                  Show this usage page and exit

**Comment by Ruijiao** [comment]
解决了，发出答案，方便其他人查阅
#--ks指定keystore 后面跟着密码  --ks-key-alias指定别名 后面跟着密码   密码都是以此开头--key-pass
  E:/sdk/build-tools/25.0.0/apksigner sign --ks test.keystore --ks-pass pass:123456 --ks-key-alias haha --key-pass pass:1234560 apnname.apk
