### ISSUE TITLE
使用configFile的时候，如果使用有 alias部分没有的设置alias的没有打出来

### ISSUE THREAD

**Issue by shibenli** [Meituan-Dianping/walle#101]
使用configFile的时候，我有部分alias设置了，还有一部分预打包alias没设置。此时预打包的这些都没有生产apk。还有当两个以上alias相同的时候没法打出来apk

**Comment by GavinCT** [comment]
1. demo里就是有写有alias 有些没有alias，也都正常生成了。 不能正常生成的举个例子？
2. alia相同时不打包很正常吧  如果使用了很少了参数 压根文件名就是一样的

**Comment by peerless2012** [comment]
我现在Config的json是u8, 在win上打出来中文别名都是乱码

**Comment by peerless2012** [comment]
已解决，执行-jar之前 加上-Dfile.encoding=utf-8即可。

**Comment by shibenli** [comment]
@GavinCT ，第一点那我再试试吧。第二点如果名称能够区分的时候呢，而且有报错信息最好了。这个倒是还好，顶多我们加序号。

**Comment by shibenli** [comment]
@peerless2012 ，这个文件编码一直是问题，建议添加文件编码设置参数，我现在是gradle打包，然后在AS启动的配置文件加你的这个参数。主要是大部分公司Android还是win，而win的这个问题还是很常见的

**Comment by GavinCT** [comment]
@shibenli 同名时报错可以，下版我们加上

**Comment by GavinCT** [comment]
@shibenli 目前代码是没有做处理的 如果alias相同，最终的file不同时 应该是生成两个文件的
完全同名时覆盖

**Comment by shibenli** [comment]
好的，谢谢
