### ISSUE TITLE
打出来的渠道包fileSHA1都相同

### ISSUE THREAD

**Issue by shibenli** [Meituan-Dianping/walle#102]
多渠道打出来的fileSHA1都相同，难道取得fileSHA1是母包的？我的理解应该是渠道包的fileSHA1，这样每个包应该是不一样的吧。

**Comment by shibenli** [comment]
![qq 20170414152612](https://cloud.githubusercontent.com/assets/7353956/25036497/cdb7e780-2126-11e7-9ad3-6cdb3772c757.png)

上面截图这是我打出来的apk的beyond比较结果

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/93
已经修复，近期会发布新版

**Comment by GavinCT** [comment]
1.1.2已经发布
