### ISSUE TITLE
关于Config.json中channelInfoList的extraInfo和defaultExtraInfo的想法

### ISSUE THREAD

**Issue by peerless2012** [Meituan-Dianping/walle#103]
有这种需求：
`defaultExtraInfo`中会定义很多`key`和`value`，`extraInfo`中会对`defaultExtraInfo`中的某些key进行覆盖，这样，如果没有写`extraInfo`，则走`defaultExtraInfo`，如果`extraInfo`有的则以`extraInfo`中为准，否则以`defaultExtraInfo`为准？

比如我在`defaultExtraInfo`加了`buildTime `和`hash`,那么肯定是想所有打出来的包都带着这几个属性，即使`extraInfo`中重写了某些值。目前是如果在`extraInfo`中重写某个key，`defaultExtraInfo`就会被忽略，感觉不太对。

**Comment by GavinCT** [comment]
这个最初时候想过。但是最终把ExtraInfo看成了一个整体，为了后面的channel能轻松过滤掉default信息。
否则default参数很多时，后面一个渠道想要屏蔽这些公有参数会变得异常复杂。

你这种case我们再考虑衡量一下吧

**Comment by GavinCT** [comment]
1. config.json新增defaultExtraInfoStrategy，用于标识当前defaultExtraInfo如何生效
    strategy:
    1. ifNone (默认适用此策略) : 仅当对应channel没有extraInfo时生效
    2. always : 所有channel都生效，channel中extraInfo的key与defaultExtraInfo重复时，覆盖defaultExtraInfo中的内容。
2. config.json新增"excludeDefaultExtraInfo": true，强制声明不使用defaultExtraInfo，默认false 

你可以使用always策略
