### ISSUE TITLE
直接运行项目，怎么没有默认的channel？

### ISSUE THREAD

**Issue by JustinChiang123** [Meituan-Dianping/walle#105]
1、第一次使用walle。
2、应该没配置错误的：能用gradlew clean assembleReleaseChannels 打包出不同channel的apk。
3、现在有个需求，怎么能直接在as中运行出来的软件包附带默认的channel。现在我直接跑出来的channel是null。

**Comment by achellies** [comment]
AS里直接运行是走的AssembleRelease，目前设计上就是想和assembleRelease区别开来，这个功能暂时不考虑添加
