### ISSUE TITLE
反编译能看到渠道吗

### ISSUE THREAD

**Issue by ananas-xxj** [Meituan-Dianping/walle#108]
我想问一下反编译之后我能 用什么办法看到或者区分渠道吗 @GavinCT

**Comment by GavinCT** [comment]
不需要反编译。 渠道号在apk的签名区，与class无关。
看渠道可以使用walle-cli 的show命令  
https://github.com/Meituan-Dianping/walle/tree/master/walle-cli

**Comment by ananas-xxj** [comment]
谢谢 @GavinCT
