### ISSUE TITLE
我项目中集成了友盟统计，然后使用walle打包后R文件报错

### ISSUE THREAD

**Issue by ImportEffort** [Meituan-Dianping/walle#109]
我项目中集成了友盟统计，然后使用walle打包后，项目的R文件总会丢失，并在所有的类中引用了com.umeng.analytics.b.g.R 这个R文件，我按照友盟的要求添加混淆规则：

-keep public class【包名】.R$*{
public static final int *;
}
并在/app/build/outputs/mapping/release/usage.txt 中找到了我们项目的 R 文件
com.goldenalpha.stock.master.R:

**Comment by GavinCT** [comment]
额 walle并不触碰这些区域 
建议你可以先打一个包 不适用walle  如果可以了再写入渠道

**Comment by ImportEffort** [comment]
@GavinCT 可是如果我不适用walle 打包我的apk 并不会造成这种情况发生

**Comment by GavinCT** [comment]
请先自己确认一下吧   issue里很多朋友都用了友盟统计 并没有什么问题。
而且walle操作区跟不可能有class相关的东西。。。

**Comment by ImportEffort** [comment]
@GavinCT  经过我的测试发现是因为 
1.  ./gradlew clean 后R文件就会丢失
2. 而使用AS 的buid——> clean 就不会出现问题
3. 单独使用 ./gradlew  assembleReleaseChannel  并不会出现R文件丢失 
4. gradle 版本是 classpath 'com.android.tools.build:gradle:2.3.1'
虽然与项目关系不是很大，也希望您可以给我解答一下 我直接使用./gradlew  assembleReleaseChannel打包时候回出现不必要的问题，如果可以请您 告诉我为什么会发生这种情况

**Comment by GavinCT** [comment]
1. clean是清除操作，相关构建产物都会消除
2. 这个应该是执行clean build两个指令了，具体我没有细看

后面没台看到，3说并不出现R文件丢失，最后问什么又说会出现不必要的问题呢？

**Comment by ImportEffort** [comment]
@GavinCT 3 的意思是说我可以直接使用 ./gradlew assembleReleaseChannel 而不是使用  ./gradlew clean assembleReleaseChannel 来进行我的多渠道打包么？ 是否会因为少了clean 操作对walle 打包产生问题？

**Comment by GavinCT** [comment]
assemble的过程会重新生成R文件才对 理论上clean并不会产生什么影响。

clean用于保证当前打包出来的apk是最新代码产物，而不是历史遗留。  与apk生成有关。与walle无关。  用不用clean都行，看个人习惯。

**Comment by cuiyue1988** [comment]
我也遇到打包之后项目的R文件消失了。 这个问题怎么解决了？

**Comment by ImportEffort** [comment]
@cuiyue1988  后来检测并不是友盟的原因 我的解决办法是使用
`./gradlew assembleReleaseChannel` 打包而不是使用文档中的：
` ./gradlew clean assembleReleaseChannel ` 指令打包

**Comment by GavinCT** [comment]
囧 你们试试不用walle插件的时候 clean是否也有问题？ 
这种不是walle插件能做到的啊 因为demo显然没有任何问题

**Comment by GavinCT** [comment]
当然不clean也没啥问题  clean只是保证是当前最新的生成结果 避免受到别的影响

**Comment by ImportEffort** [comment]
@GavinCT  使用 studio 自带的 clean 方法就好使，如果使用 gradle 进行 ./gradlew clean 出现问题 ，stuido 版本2.3 就会出问题

**Comment by CrazyStoneJy** [comment]
恩，我也出现了这个问题，这可能是android studio的bug!

**Comment by CrazyStoneJy** [comment]
@ImportEffort

**Comment by popmj007** [comment]
这个问题我也出现了
