### ISSUE TITLE
打出来只有一个release 包

### ISSUE THREAD

**Issue by xiaozhicheng** [Meituan-Dianping/walle#116]
是按你的步骤来打的，求解

**Comment by GavinCT** [comment]
这种问法是没法帮你解决问题的  你运行下demo看看  成功以后再看看自己哪里用错了把

**Comment by xiaozhicheng** [comment]
// 渠道配置文件
    channelFile = new File("${project.getProjectDir()}/channel")是这里应该是 channel.text

**Comment by GavinCT** [comment]
。。。 取决于你的文件名。。。
