### ISSUE TITLE
批量打包怎么修改AndroidManifest.xml文件？

### ISSUE THREAD

**Issue by cuiyue1988** [Meituan-Dianping/walle#117]
批量打包时候 如何替换 AndroidManifest文件里面的内容 比如：替换下面的XXX

    <meta-data
            android:name="UMENG_CHANNEL"
            android:value="XXX" />

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/74

**Comment by cuiyue1988** [comment]
谢啦~~~~
