### ISSUE TITLE
编译时报support-annotations的包冲突，项目中已有了SUPPORT-V4，如何解决呢？

### ISSUE THREAD

**Issue by vlong5461** [Meituan-Dianping/walle#119]
编译时报support-annotations的包冲突，项目中已有了SUPPORT-V4,如何解决呢？谢谢！
(Duplicate zip entry [support-annotations-24.1.1.jar:android/support/annotation/BinderThread.class]))

**Comment by GavinCT** [comment]
提供下详细的compile？   support-v4哪个版本 
walle library里依赖了 support-annotations

**Comment by vlong5461** [comment]
已解决，添加support-v4时移除 support-annotations包
compile ('com.android.support:support-v4:24.1.1'){
        exclude module: 'support-annotations'
    }
