### ISSUE TITLE
gradle3.3中没有getAndroidGradlePluginVersion()

### ISSUE THREAD

**Issue by duzechao** [Meituan-Dianping/walle#12]
com.android.tools.build:gradle:2.3.0-beta2  gradle3.3中getAndroidGradlePluginVersion 被com.android.builder.Version.ANDROID_GRADLE_PLUGIN_VERSION替代，导致插件出错
可以使用getGradle().getGradleVersion()或com.android.builder.Version.ANDROID_GRADLE_PLUGIN_VERSION

**Comment by achellies** [comment]
#13

**Comment by GavinCT** [comment]
try 1.0.3
