### ISSUE TITLE
为什么用第一种方式集成会生成多cpu类型的包

### ISSUE THREAD

**Issue by ocean143** [Meituan-Dianping/walle#121]
为什么用第一种方式集成会生成多cpu类型的包，这让我感到很诧异。

**Comment by GavinCT** [comment]
splits {
        abi {
            enable true
            reset()
            include 'armeabi', 'x86'
            universalApk false
        }
    }

因为配置里本身区分了abi

**Comment by GavinCT** [comment]
没啥好诧异的
