### ISSUE TITLE
Error:(47, 0) Could not find method manifestPlaceholders() for arguments 

### ISSUE THREAD

**Issue by puretsang** [Meituan-Dianping/walle#122]
App  build.gradle
productFlavors{
        Beta{
            buildConfigField "int", "ENV_TYPE", "1"
            applicationId "com.shixin.yuezi_beta"
            manifestPlaceholders {
                app_name="仕馨月子会所Dev(二期)"
                app_icon="@mipmap/ic_launcher_beta"
            }
        }
        Test{
            buildConfigField "int", "ENV_TYPE", "2"
            applicationId "com.shixin.yuezi_test"
            manifestPlaceholders {
                app_name="仕馨月子会所Test(二期)"
                app_icon="@mipmap/ic_launcher_beta"
            }
        }
        //通用版
        general {
            buildConfigField "int", "ENV_TYPE", "3"
            manifestPlaceholders {
                app_name="仕馨月子会所(二期)"
                app_icon="@mipmap/ic_launcher"
            }
        }
    }

我的清单文件
    <application
        android:name=".ui.APP_Sx"
        android:allowBackup="true"
        android:icon="${app_icon}"
        android:label="${app_name}"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:replace="android:icon,android:theme">

error:
Error:(47, 0) Could not find method manifestPlaceholders() for arguments [build_dabfhunduacdiqdnfy7zyy6j7$_run_closure1$_closure5$_closure14$_closure17@6c18f5a] on ProductFlavor_Decorated{name=Beta, dimension=null, minSdkVersion=null, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=com.shixin.yuezi_beta, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={ENV_TYPE=com.android.builder.internal.ClassFieldImpl@5809cd74}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.<a href="openFile:/Users/waikeytsang/shixin_huisuo/app/build.gradle">Open File</a>

**Comment by GavinCT** [comment]
加上--stacktrace发一下看看

**Comment by GavinCT** [comment]
??  一直没回复就先关闭了 有信息再同步
