### ISSUE TITLE
如何动态写入参数

### ISSUE THREAD

**Issue by panda912** [Meituan-Dianping/walle#123]
如果 versionCode 设置是当前时间，如何动态写入？

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/tree/master/walle-cli

**Comment by GavinCT** [comment]
备注一下：   
如果是apk里的versionCode  可以通过defaultConfig来做修改，这不属于walle的范畴。比如下面这种：
```
defaultConfig {
        versionCode System.currentTimeMillis().intValue()
    }
```
或者其他自己google一下。  
如果你提到的versionCode是想写入walle区域的话，可以用cli  写个shell配合使用即可。相比于plugin，cli的可定制性较高
