### ISSUE TITLE
提示没有这个任务。。。assembleReleaseChannels

### ISSUE THREAD

**Issue by sooner0493** [Meituan-Dianping/walle#124]
提示没有这个任务。。。assembleReleaseChannels 是怎么回事呢~求助

**Comment by sooner0493** [comment]
然而指定渠道以后能用了 ，要使用这个任务必须把渠道配置删掉。。。

**Comment by GavinCT** [comment]
> 然而指定渠道以后能用了 ，要使用这个任务必须把渠道配置删掉。。。
希望能表述清楚一些 没看懂

**Comment by sooner0493** [comment]
哦 抱歉。 我是这意思:productFlavors {
        baidu {}
    }有这个得话，assembleReleaseChannels就提示找不到任务；去掉就好了

**Comment by GavinCT** [comment]
注意看readme：

> 用法示例：
> 生成渠道包 ./gradlew clean assembleReleaseChannels
> 支持 productFlavors ./gradlew clean assembleMeituanReleaseChannels

**Comment by sooner0493** [comment]
收到，我理解错了

**Comment by yanxinmiao** [comment]
@GavinCT 
支持 productFlavors ./gradlew clean assembleMeituanReleaseChannels

以上命令中的 "Meituan" , 是productFlavors  中定义的任意一个吗 ？

**Comment by QHM-MING** [comment]
@GavinCT 
执行 productFlavors ./gradlew clean assembleMeituanReleaseChannels 
其中Meituan替换为 productFlavors 中的部分包，但打出来的还是channel中包含的渠道包
如何处理

**Comment by GavinCT** [comment]
@QHM-MING 没看懂你的意思   这个指令就是有channel啊
