### ISSUE TITLE
 pack name命名支持gitSha 命名

### ISSUE THREAD

**Issue by dev4mobile** [Meituan-Dianping/walle#125]
gitSha  #获取方式：
def gitSha = 'git rev-parse --short HEAD'.execute([], project.rootDir).text.trim()
🍻

**Comment by GavinCT** [comment]
类似自定义的需求可能很多，我们考虑一下怎么开放自定义能力

**Comment by banxi1988** [comment]
@dev4mobile 
话说,gitSha直接通过 buildConfigField 配置就行了.
例如:

```groovy
  buildConfigField "String","BUILD_SOURCE_VERSION","\"${gitSha}\""
```
