### ISSUE TITLE
Walle CLI 使用说明 README有问题

### ISSUE THREAD

**Issue by liuhea** [Meituan-Dianping/walle#126]
Walle CLI 使用说明中，指定渠道配置文件有误
<img width="939" alt="wx20170611-002108 2x" src="https://user-images.githubusercontent.com/19663285/27004465-0a696018-4e3c-11e7-9db9-878be235ebd0.png">

**Comment by GavinCT** [comment]
hi  这里对应的是这个文件 https://github.com/Meituan-Dianping/walle/blob/master/app/channel  因为本身没加文件类型 所以也没有在cli里指明 
so 两者一一对应就好。
mac、linux中不加文件类型挺常见的，在windows上如果看着不习惯可以自己加上，只要指定时对应上就好。

**Comment by liuhea** [comment]
没有注意到，下载下来的是txt。 我想问一下,在Maniefest中需要设置UMENG_CHANNEL是否受影响？

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/74

**Comment by liuhea** [comment]
不好意思，我可能觉得那是也是别人想问的问题吧。

**Comment by GavinCT** [comment]
@liuhea 嗯嗯 没事 那位同学的问题已经解决  和你说的一样 代码设置 而不是使用清单文件。
因为清单文件的方式必须重新打包。  walle之所以速度快就是保证apk也就是zip的内容区一直不变，其中自然也包括清单文件，多渠道的实现借助v2签名区，需要做的就是copy多分apk文件，然后再v2区吸入信息。 可以看下博客，了解下原理
