### ISSUE TITLE
打包命令不完美

### ISSUE THREAD

**Issue by dev4mobile** [Meituan-Dianping/walle#127]
现在打包命令./gradlew clean assembleReleaseChannels(没有 checkstyle， lint检查， 单元测试)
往往打包命令都是./gradlew clean build  [包含了checkStyle， lint， 单元测试等)

能否 clean build 先打一个基础包，然后再打签名渠道包

**Comment by dev4mobile** [comment]
@achellies @GavinCT

**Comment by GavinCT** [comment]
可以 用正常的打包命令出一个基础包 然后cli直接写入签名即可
> 能否 clean build 先打一个基础包，然后再打签名渠道包

**Comment by dev4mobile** [comment]
用cli  太不不自动化了

**Comment by GavinCT** [comment]
写到一个shell脚本里即可。   先assemble 后cli  很正常啊
lint task默认指挂到assemble release的时候 除非指定lint执行  如果非让walle弄得话 就只能放在assemble后面 容易影响正常打包

**Comment by dev4mobile** [comment]
👌
