### ISSUE TITLE
命令行指定渠道&额外信息配置文件如何指定输出apk的名字

### ISSUE THREAD

**Issue by h1091129209** [Meituan-Dianping/walle#130]
用Java命令行指定渠道&额外信息配置文件生成的apk如何按指定apk名字输出，默认是在原来的名字后加的渠道号，但是我想输出${
channel}-${versionName}-${buildType}.apk

**Comment by GavinCT** [comment]
注意区分概念 cli的话 因为是指定了输入apk  所以输出是固定的加channel
既然是自己指定的apk  那么versionName、buildType不是自己已知么？ 
另：
1. 如果仅仅在意是channel放在前面和后面的问题，可以通过shell脚本自己再改一下
2. buildtype本身这时候从apk里也已经拿不到了

**Comment by GavinCT** [comment]
plugin之所以支持是因为他知道整个打包过程，知道这些参数，所以允许格式化

**Comment by h1091129209** [comment]
改了一下generateChannelApk方法里的apk命名规则，解决了这个问题

**Comment by GavinCT** [comment]
👌

**Comment by h1091129209** [comment]
这个要是还可以打包Android Signature V1 Scheme签名的就好了，应用宝的居然不支持Android Signature V2 Scheme的包

**Comment by GavinCT** [comment]
应用宝最新的版本已经支持 应该是应用宝7.0开始支持的

**Comment by h1091129209** [comment]
早两天上传的游戏都提示不支持Android Signature V2 Scheme

**Comment by GavinCT** [comment]
额 这个。。。可能需要你们找他们协调一下吧
支持v1的话其实会耗时，因为支持v1就需要重新打包，所以两种方案很难融合。v1的写入区域都会导致v2校验不过

**Comment by h1091129209** [comment]
嗯
