### ISSUE TITLE
在application中获取渠道并调用第三方统计（bugly，友盟），渠道未设置上

### ISSUE THREAD

**Issue by lxc7923** [Meituan-Dianping/walle#131]
private void initChannel() {
        String channel = WalleChannelReader.getChannel(this.getApplicationContext());
        Ln.e(" Channel :" + channel);
        MobclickAgent.startWithConfigure(new MobclickAgent.UMAnalyticsConfig(getContext(), "569892cee0f55a6e97001be8", channel));
        Bugly.setAppChannel(getContext(), channel);
    }

我在application类一进来就设置了，最奇怪的是有的渠道如baidu都设置上了，但很多如应用宝都是unknown渠道，有没有什么可能的原因呢？

**Comment by GavinCT** [comment]
应用宝的6.7版本以下 他们自带的增量更新  不支持v2签名 会丢失v2签名区 注意 是他们的增量更新，全量更新是正常的。
7.0以上他们修复了，增量更新是正常的

**Comment by lxc7923** [comment]
是不是walle默认就是v2方式签名呢？能否设置v1方式？

**Comment by GavinCT** [comment]
使用v1签名的时候其实就是一代打包方案，没必要使用walle啊

**Comment by dazeGitHub** [comment]
我也遇到同样的问题了，百度统计设置不上
