### ISSUE TITLE
插件获取最新版本aar，一旦发版导致所有用户被迫升级

### ISSUE THREAD

**Issue by githubliruiyuan** [Meituan-Dianping/walle#133]
Error:A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > Could not find payload_reader.jar (com.meituan.android.walle:payload_reader:1.1.4).
     Searched in the following locations:
         https://jcenter.bintray.com/com/meituan/android/walle/payload_reader/1.1.4/payload_reader-1.1.4.jar

**Comment by GavinCT** [comment]
hi  这是网络问题 没拿到jar包   => GFW

**Comment by GavinCT** [comment]
我这边是可以下载的 请检查下网络

**Comment by githubliruiyuan** [comment]
重点是我用的是1.1.3,不应该出现这个才对

**Comment by GavinCT** [comment]
查一下dependencies是谁把版本给你带上去的   指定版本号之后并不会自动升级

**Comment by GavinCT** [comment]
sorry review了下代码，发现之前有次提交里改动了获取版本：插件默认获取最新aar 
后面插件会改掉
你先试试在aar的compile加上force=true

**Comment by githubliruiyuan** [comment]
赞

**Comment by githubliruiyuan** [comment]
Could not find plugin.jar (com.meituan.android.walle:plugin:1.1.4). 升级最新还是不行

**Comment by GavinCT** [comment]
还是我说的 网络不好
你强制自己的aar是1.1.3版本  插件也先不升级，用本地缓存

**Comment by GavinCT** [comment]
1.1.5版本已发布，以后不会再因为新版本发布而提醒用户了~
