### ISSUE TITLE
预装在系统system\priv-apps目录下的应用无法获取到渠道号

### ISSUE THREAD

**Issue by JiawenZhou1** [Meituan-Dianping/walle#134]
使用Walle生成渠道号，手动安装的应用获取都没有问题。但是预置在系统system\priv-apps目录下后，启动应用获取不到渠道号。

多谢。

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/blob/master/library/src/main/java/com/meituan/android/walle/WalleChannelReader.java
你自己调试改造下library里的代码吧  这个场景订制化太高，应该是apk路径不对吧 
这段代码调试下看看：
```java
@Nullable
  | private static String getApkPath(@NonNull final Context context) {
  | String apkPath = null;
  | try {
  | final ApplicationInfo applicationInfo = context.getApplicationInfo();
  | if (applicationInfo == null) {
  | return null;
  | }
  | apkPath = applicationInfo.sourceDir;
  | } catch (Throwable e) {
  | }
  | return apkPath;
  | }
```

**Comment by GavinCT** [comment]
hi  如果确认问题了还请回复下  没啥其他问题的话 我就关闭了

**Comment by GeorgeBin** [comment]
你好，我也遇到了这个问题。

通过测试发现，并不是路径获取错误产生的问题。
而是在内置的过程中，apk包内写入的渠道信息丢失了。（并没有重新签名）

请问，该如何处理？
