### ISSUE TITLE
应用重启，补丁应用成功后，会弹出是否重启的确认框，点击重启后，并没有重新启动

### ISSUE THREAD

**Issue by qq451682583** [Meituan-Dianping/walle#135]
如题所述，logcat看日志，Application的部分代码会执行，但是app没有成功启动

**Comment by GavinCT** [comment]
哥们，你是不是走错房间了

**Comment by mivanzhang** [comment]
哥们，你应该加上堆栈，去robust项目 https://github.com/Meituan-Dianping/Robust/issues

**Comment by qq451682583** [comment]
走错片场了 。
