### ISSUE TITLE
用walle打包有没有办法根据不同的包更改 resValue 和 buildConfigField

### ISSUE THREAD

**Issue by qq2748** [Meituan-Dianping/walle#136]
形如:
productFlavors {
    vivob{ resValue "string", "app_name", "xxx-xxx网"; resValue "string", "launcher_name", "xxx"; buildConfigField "boolean", "SHOW_RECOMMOND", "false"; }
}

**Comment by GavinCT** [comment]
这是flavor干的事情啊  请注意区分flavor和channel的使用
这种情况你可以打多个flavor的包    如果flavor相同，还想区分使用channel

**Comment by qq2748** [comment]
明白,  但是如果每个渠道都有不一样的resValue, buildConfigField的话 flavor就会很多, 这时候用不用walle 打包的速度区别不大了?

**Comment by GavinCT** [comment]
如果只是你写的这些的话  可以改用walle的extraInfo记录
写个脚本 用cli写入不同的extraInfo

**Comment by GavinCT** [comment]
其实channel只是用来在flavor相同的情况下使用。如果flavor不同只是一些变量，倒是可以用extraInfo，如果flavor中还有不同的代码和资源就不建议了。
或许你可以整理下你们的flavor使用，看是否有必要

**Comment by qq2748** [comment]
👌好的感谢

**Comment by GavinCT** [comment]
比如SHOW_RECOMMOND  其实多数情况下应该没必要使用builconfig  可能你多个flavor都是true 只有一两个事false ，其实这和在代码里写死也没啥区别。（if channel == "xxx")
相反使用buildConfig你每次新增一个flavor，都在gradle里写很多，多数情况都是重复的，我个人觉得是没有必要的。代码里写一眼就看见哪个渠道是true  哪个是false   写在flavor里反倒不容易查找。

**Comment by GavinCT** [comment]
flavor的使用推荐是代码、资源不同，如果只是一两个变量，为了打包速度和代码好看，谨慎使用为好。
很少见每个渠道都是不同的flavor。
美团就只有三四个flavor，是特殊市场订制包，其他多数市场都是main flavor下的channel包。
仅供参考

**Comment by qq2748** [comment]
恩是的, 我司的打包需求变动比较大 , 每个版本这些变量都不同, 所以才有这样的写法

**Comment by GavinCT** [comment]
ok 那可能需要你们根据自己情况选择了

**Comment by huangchaoqingcheng** [comment]
我需要在不同渠道对应不同的应用图标，，这种情况是不是就不适用了，，，
