### ISSUE TITLE
用命令行打渠道包时报以下错误

### ISSUE THREAD

**Issue by guangxingmao** [Meituan-Dianping/walle#137]
* What went wrong:
Task 'assembleReleaseChannels' not found in root project 'Ztbandroid'. Some candidates are: 'assemblePpReleaseChannels'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by GavinCT** [comment]
hi 仔细看提示啊  提示里面写了 让你用assemblePpReleaseChannels
readme里也说了 因为支持flavor 所以你又flavor自然就需要加上flavor了
