### ISSUE TITLE
渠道存在被更改的安全问题如何解决？

### ISSUE THREAD

**Issue by xuezhangbin** [Meituan-Dianping/walle#139]
如何能够避免被更改渠道呢？只要知道id之后，替换value（我们也考虑过加密数据，可是别人也可以拿一个我们加密过的渠道读取加密数据，然后直接赋值这个加密数据）即可。 

感谢感谢。

**Comment by GavinCT** [comment]
额 是不是涉及到渠道推广费用结算？  如果是，我个人这么理解：
- 渠道是写完以后给各大应用市场的，他们一般不会更改。
- 通过一些非常规推广，怕修改影响结算。这种问题似乎也不大，后台只计算自己认证的渠道，随便搞渠道的不计入。然后认证的之间如果单台设备只能结算一个渠道的话，似乎也只是你用别人渠道自己渠道就减少的零和博弈，也没啥问题吧。如果设备增长了，那也没啥问题啊

如果不涉及费用结算，好像渠道被改也没啥大问题。

so，你们的痛点最好描述一下，或者 这是个伪需求？

**Comment by xuezhangbin** [comment]
感谢回答。
主要影响非常规渠道的结算。 因为非常规渠道是根据自己写入的渠道号来结算，存在呗篡改的可能就可能影响结算。 比如A渠道把  B渠道的包改成了自己的渠道，可以通过拦截包，重新更改写入方式。  那这也是我们认证的渠道号。

**Comment by GavinCT** [comment]
> 如果单台设备只能结算一个渠道的话，似乎也只是你用别人渠道自己渠道就减少

感觉推广方应该保证自己的推广可靠吧  sorry 没get到有什么去恶意更改的动机

**Comment by xuezhangbin** [comment]
好的，谢啦。
