### ISSUE TITLE
配置productFlavors后，无法生成多个渠道包

### ISSUE THREAD

**Issue by hesshzy** [Meituan-Dianping/walle#143]
使用Gradle插件使用方式使用walle
```
buildscript {
    dependencies {
        classpath 'com.meituan.android.walle:plugin:1.1.4'
    }
}
```
```
apply plugin: 'walle'

dependencies {
    compile 'com.meituan.android.walle:library:1.1.4'
}
```
```
walle {
    // 指定渠道包的输出路径
    apkOutputFolder = new File("${project.buildDir}/outputs/channels");
    // 定制渠道包的APK的文件名称，自定义获取时间的方法readDate
    apkFileNameFormat = 'parent_${versionName}_${flavorName}_${buildType}_' + "${readDate()}.apk";
    // 渠道配置文件
    channelFile = new File("${project.getProjectDir()}/channel")
}
def readDate() {
    return new Date().format("yyyyMMdd")
}
```
channel文件
```
anzhi # 安智
appchina # 应用汇
baidu
#  其他省略
```

### 配置了productFlavor
```gradle
    productFlavors {
        app {}
        meituan {}
        QQ {}
        //省略其他渠道
    }
```

执行```gradlew assembleReleaseChannels```时，提示
```
* What went wrong:
Task 'assembleReleaseChannels' not found in root project 'babychat'. Some candidates are: 'assembleAppReleaseChannels'.
```

执行```gradlew assembleAppReleaseChannels```时，可以成功生成1个apk。

执行```gradlew assembleAppReleaseChannels -PchannelList=baidu,huawei,Lenovo,m360,oppo,QQ,smartisan,vivo,wandoujia,xiaomi```时，参数无效，还是只生成1个apk。

### 希望在配置productFlavors时可以一键生成多个渠道包

**Comment by GavinCT** [comment]
已经支持的~  
贴一下自己的插件版本号以及walle的插件配置

**Comment by wardenlzr** [comment]
@GavinCT Task 'assembleReleaseChannels' not found in root project 'AndroidApp'.
大佬你好，我加了productFlavors后报这个错，是什么问题哇？
FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleReleaseChannels' not found in root project 'AndroidApp'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

我使用gradlew tasks  是成功的

项目的Gradle如下
buildscript {
    repositories {
        jcenter()
        mavenCentral() // add repository
        maven { url "https://jitpack.io" }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2' // add plugin
        classpath 'com.qihoo360.replugin:replugin-host-gradle:2.2.0'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.7.0'
        classpath 'com.qihoo360.replugin:replugin-plugin-gradle:2.2.0'

        classpath 'com.meituan.android.walle:plugin:1.1.6'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
App的Gradle如下：
apply plugin: 'com.android.application'
apply plugin: 'android-apt'             //butterknife简便控件库
apply plugin: 'org.greenrobot.greendao' //greendao数据库
apply plugin: 'walle'

android {
    compileSdkVersion 25
    buildToolsVersion "26.0.0"

    defaultConfig {
//        applicationId "***"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 3
        versionName "3.2.3"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        multiDexEnabled true
    }
    signingConfigs {
        sankuai {
            storeFile file("**")
            storePassword "123456"
            keyAlias "key0"
            keyPassword "123456"
        }
    }
    buildTypes {
        /*release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }*/
        //混淆
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.sankuai
        }
    }
    tasks.whenTaskAdded { task ->
        if (task.name.contains("lint")
//如果instant run不生效，把clean这行干掉
//                ||task.name.equals("clean")
                //如果项目中有用到aidl则不可以舍弃这个任务
                || task.name.contains("Aidl")
//用不到测试的时候就可以先关闭
                || task.name.contains("mockableAndroidJar")
                || task.name.contains("UnitTest")
                || task.name.contains("AndroidTest")
//用不到NDK和JNI的也关闭掉
//                || task.name.contains("Ndk")
//                || task.name.contains("Jni")
        ) {
            task.enabled = false
        }
    }
    greendao {
        schemaVersion 1
//        daoPackage 'com.koma.greendao.gen'
//        targetGenDir 'src/main/java'
    }
    //强制统一V7包
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '25.3.1'
                }
            }
        }
    }
    android.applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                def fileName = "移动执法_V${defaultConfig.versionName}.apk"
                output.outputFile = new File(outputFile.parent, fileName)
            }
        }
    }
    productFlavors {
        //debug版本,调试用
        common {
            applicationId "**"
        }
        nj_aly {
            applicationId "com.*.android"
        }
        nj_xs  {
            applicationId "com.**.android"
        }

    }
    //解决不能运行到64位CPU
    /*splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a'
            universalApk true
        }
    }*/
    /*sourceSets {
        main() {
            jniLibs.srcDirs = ['libs']
        }
    }*/
}
configurations {
    commonCompile
    nj_alyCompile
    nj_xsCompile
}
apply plugin: 'replugin-host-gradle'    //replugin插件化框架
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
   ...
    compile 'com.meituan.android.walle:library:1.1.6'
}
walle {
    apkOutputFolder = new File("${project.buildDir}/outputs/channels")
    apkFileNameFormat = '多渠道_${appName}-${packageName}-${channel}-${buildType}-v${versionName}-${versionCode}-${buildTime}-${flavorName}.apk'
    //configFile与channelFile两者必须存在一个，否则无法生成渠道包。两者都存在时优先执行configFile
    channelFile = new File("${project.getProjectDir()}/channel")
    //configFile = new File("${project.getProjectDir()}/config.json")
}

**Comment by GavinCT** [comment]
assembleReleaseChannels  你没有Release这个flavor

**Comment by xingguanghuanye** [comment]
我也是配置了productFlavors之后报这个错，在package里面也没有找到assembleReleaseChannels，这个和gradle的版本有关吗，我使用的是classpath 'com.android.tools.build:gradle:3.1.3'，distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip，walle是使用的最新版
