### ISSUE TITLE
打包异常

### ISSUE THREAD

**Issue by songwj1989** [Meituan-Dianping/walle#145]
命令为：gradlew clean assembleReleaseChannels -PchannelList=xiaomi

异常：A problem was found with the configuration of task ':app:packageXiaomiRelease'.
> File 'E:\StudioProjects\walle_demo\app\build\intermediates\res\resources-release-stripped.ap_' specified for property 'resourceFile' does not exist.

res下面是resources-release.ap_

**Comment by GavinCT** [comment]
建议先试下没有assembleRelease是够可以正常运行

**Comment by songwj1989** [comment]
已经调通了。把混淆、移除无用的resource这些关掉就可以了。。。
buildTypes {
        release {
            /**
             * 用到walle多渠道打包插件时，
             * 以下三个设置为false；否则打包会失败。
             */
            //混淆
            minifyEnabled false
            //Zipalign优化
            zipAlignEnabled false
            // 移除无用的resource文件
            shrinkResources false

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.release
        }
}

**Comment by GavinCT** [comment]
额  walle是支持混淆和shrink的。。。 你可能有其他插件在影响
还是那个建议：
> 建议先试下没有assembleRelease是够可以正常运行

**Comment by songwj1989** [comment]
好的，我试试

**Comment by songwj1989** [comment]
貌似不行，debug模式才行。

**Comment by GavinCT** [comment]
所以与walle无关，你的Release本身就不知道被什么插件或者什么东西给污染了把~~

**Comment by songwj1989** [comment]
好吧。我把上面的给去掉试试：
        // ButterKnife插件
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'

        // bugly统计插件集成的tinker热修复插件
        classpath "com.tencent.bugly:tinker-support:1.0.8"

        // walle多渠道打包插件
        classpath 'com.meituan.android.walle:plugin:1.1.3'

**Comment by BananaHuo** [comment]
> 好吧。我把上面的给去掉试试：
> // ButterKnife插件
> classpath 'com.jakewharton:butterknife-gradle-plugin:8.4.0'
> classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
> 
> ```
>     // bugly统计插件集成的tinker热修复插件
>     classpath "com.tencent.bugly:tinker-support:1.0.8"
> 
>     // walle多渠道打包插件
>     classpath 'com.meituan.android.walle:plugin:1.1.3'
> ```

请教下你是怎么解决的呢？我的Windows可以用realease 但是用mac 就不能打realease  不知道是被啥插件影响了混淆
