### ISSUE TITLE
// 渠道&额外信息配置文件，与channelFile互斥     configFile = new File("${project.getProjectDir()}/news.json") 

### ISSUE THREAD

**Issue by xiongyingjun** [Meituan-Dianping/walle#146]
配置json文件中的alias 属性命名的中文，打包出现乱码

**Comment by GavinCT** [comment]
注意json文件是utf-8编码
app里有demo，可以试下，是没有问题的

**Comment by xiongyingjun** [comment]
我就是用demo中的json文件,还是会乱码

**Comment by GavinCT** [comment]
windows？

**Comment by xiongyingjun** [comment]
嗯
![qq 20170807092936](https://user-images.githubusercontent.com/16781036/29010426-d49ce3e8-7b5d-11e7-83d6-1ed0f959244c.png)
![qq 20170807093002](https://user-images.githubusercontent.com/16781036/29010427-d4f9ea98-7b5d-11e7-8a1a-8addb0b89734.png)

**Comment by GavinCT** [comment]
你手动转换下编码格式？？  mac下没问题 囧

**Comment by xiongyingjun** [comment]
你指的是转文件还是工具的？

**Comment by GavinCT** [comment]
文件啊

**Comment by xiongyingjun** [comment]
编码格式是utf-8的，没错

**Comment by GavinCT** [comment]
今天会发版修复
读取文件时用了FileReader，使用平台默认的charset导致。

**Comment by xiongyingjun** [comment]
好的，谢谢

**Comment by GavinCT** [comment]
请使用1.1.5版本

**Comment by xiongyingjun** [comment]
亲测，可用，666
