### ISSUE TITLE
引用报错：java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by lijian8742** [Meituan-Dianping/walle#148]
具体错误如下：
* What went wrong:
A problem occurred evaluating root project 'JoyinWiseSeller_three'.
> java.lang.UnsupportedClassVersionError: com/android/build/gradle/AppPlugin : Unsupported major.minor version 52.0

在build.gradle中去掉walle相关配置之后是可以正常使用的，不知道是什么问题。。我这边用的JDK版本是1.7的。  网上有的说要升级JDK到1.8，我想在不更换JDK版本的情况如果解决这个问题？

**Comment by GavinCT** [comment]
不好意思哈  我们现在用java8打包的

**Comment by lijian8742** [comment]
现在没办法兼容java7？
