### ISSUE TITLE
预装在系统/system/app 目录下的应用无法获取到渠道号

### ISSUE THREAD

**Issue by GeorgeBin** [Meituan-Dianping/walle#149]
之前有人提过类似的issue: [issue-134](https://github.com/Meituan-Dianping/walle/issues/134)

参考了给出的建议：apk路径获取不正确

根据建议，我进行了测试，获取的路径是没有问题的，我通过将预装后的apk文件备份出来，通过walle-cli-all.jar 的 show命令查看，是没有渠道信息的(预装前的apk文件查看是有渠道信息的)。

所以想问下，预装过程会对写入的渠道号，有什么影响？

备注：预装过程，没有对apk使用系统签名文件进行重新签名。

**Comment by GavinCT** [comment]
确认下你提供出去apk是否有信息，然后如果有，预装过程中消失了，你似乎应该找一下预装厂商  问下他们做过啥

**Comment by GeorgeBin** [comment]
发出去的apk有渠道信息，预装之后，渠道信息就消失了，app内读取不到，使用walle-cli-all.jar 也读取不到。

问预装厂商，他们说是正常预装流程，也没有重新签名……

**Comment by GavinCT** [comment]
> 使用walle-cli-all.jar 也读取不到。
你把预装的apk拉出来 用jar也读不到？？  那就是信息被抹除了啊 没有别的解释~~

**Comment by GeorgeBin** [comment]
那结论就是：在预装apk的过程中，渠道信息会丢失。

那后期有没有计划会适配这种情况，或者查找原因，给出一个建议的解决办法呢？

**Comment by GavinCT** [comment]
囧。。 这种情况不是walle造成的啊
你需要问下 为啥从你这里给出的包 不是最后的预装包啊。  你给他们的是有渠道的包，他们预装之后是没有渠道的包，也就是说他预装的包改动了。。。这显然应该是商业上沟通的事情，与技术无关啊
walle开发人员给不了什么解释啊~

**Comment by GeorgeBin** [comment]
好的，明白~~

**Comment by byerman** [comment]
你好，我也碰到这个问题，请问你后续和厂商沟通，有知道是什么原因导致的吗

**Comment by byerman** [comment]
> 好的，明白~~

你好，我也碰到这个问题，请问你后续和厂商沟通，有知道是什么原因导致的吗
