### ISSUE TITLE
walle只能用 V2签名吗？设置 v1SigningEnabled true 打多渠道包或者 assembleRelease 打出来的包为V1签名包，到执行 assembleReleaseChannels 时直接报 app-release.apk has no v2 signature in Apk Signing Block!

### ISSUE THREAD

**Issue by CoralXss** [Meituan-Dianping/walle#150]
和 issue #76 AndResGuard 相关。
这边也使用了 AndResGuard 进行资源混淆，执行 gradle assembleRealeaseChannels 打多渠道包，查看 build 日志，是这样的流程：先打realse 包，然后是AndResGuard对 apk目录下的包进行资源混淆，得到混淆后的 release 包，这个包好像不管开没开启 V2签名，最后混淆资源得到的包都是 V1签名，之后就是 walle 打多渠道包了，这一步看源码是要检验 V2签名的，直接就编译失败，打包日志如下：
……
zipaligning apk: app-release_signed.apk
zipaligning apk app-release_signed_aligned.apk done, file reduce: 216.854492kb, time cost from begin: 8.857000s
resources proguard done, total time cost: 8.857000s
resources proguard done, you can go to file to find the output ……/app/build/resourceproguard
resources proguard apk replace done, you can go to file to find the output ……/app/build/outputs/apk/app-release.apk
:app:assembleReleaseChannels FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:assembleReleaseChannels'.
> ……/app/build/outputs/apk/app-release.apk has no v2 signature in Apk Signing Block!

**Comment by GavinCT** [comment]
walle只支持v2   如果使用v1的话 没必要用walle啊  用美团老的渠道包方式即可

**Comment by monkey008** [comment]
可是v2不是只支持Android7.0以上的版本么？walle只支持v2的话打出的渠道包应该无法在Android7.0以下安装吧？这样还是我理解的有误？

**Comment by GavinCT** [comment]
你理解错了 向下不兼容的话。。谁会升级v2呢

**Comment by monkey008** [comment]
但是我记得之前用as打包时如果只勾选v2的话 Android7.0安装时会提示未安装，除非v1、v2都勾选或者只勾选v1才兼容
