### ISSUE TITLE
不太理解"加固未签名的包"

### ISSUE THREAD

**Issue by xsslong** [Meituan-Dianping/walle#154]
不太理解"加固没签名的包", 既然加固上传的包是release包,  release包就是签名了的包啊?加固步骤我理解的是:
1.加固签名的包;
2.下载加固好的包;
3.将加固好的包重新签名.
怎么做到加固没签名的包?

**Comment by xsslong** [comment]
理解了, 加固没签名的包实在加固完成后不要直接使用签名工具签名, 使用apksigner sign --ks命令行签名, 签名完后, 使用CheckAndroidV2Signature.jar检测签名情况, 最后再导入渠道信息.并不是加固没签名的包, 而是生成的加固包不要直接使用签名工具签名.

**Comment by StephenGiant** [comment]
如果没配置debug和release的专属配置的话 其实也没什么区别
