### ISSUE TITLE
如何动态修改应用的名称？

### ISSUE THREAD

**Issue by renzhenfei** [Meituan-Dianping/walle#156]
首先非常感谢您选用Walle。

Walle还有很多不足，在已经关闭的issue中我们解决了很多问题，在提交新issue时，可以去已经[关闭的issue中寻求答案](https://github.com/Meituan-Dianping/walle/issues?q=is%3Aissue+is%3Aclosed)。

为了更好的帮助我们定位问题，请在提issue时携带尽可能多的日志或者说明。

**Comment by renzhenfei** [comment]
根据渠道名称

**Comment by GavinCT** [comment]
非walle问题请自行google

**Comment by renzhenfei** [comment]
就是使用walle的时候啊，我如果使用productFlavors的话是可以的

**Comment by GavinCT** [comment]
walle是针对flavor包做channel的 
注意看readme描述
