### ISSUE TITLE
已解决：集成walle之后，高德地图白屏（高德的锅）

### ISSUE THREAD

**Issue by zyktojo** [Meituan-Dianping/walle#158]
我是安卓开发者，项目里用到了高德地图
集成了walle之后，我项目的高德地图运行即白屏
更狗血的是，我回退了git版本之后，地图依然白屏
因此我怀疑walle改变了我项目的文件内容或结构

据我了解，高德地图使用了自定义View，并且使用了Asset资源文件，
并且不兼容某些自定义打包工具，
高德官方的三种解决办法全试过了，不管用：
http://lbs.amap.com/faq/android/android-map/349

**Comment by zyktojo** [comment]
由于walle给我项目结构造成的不可逆的改变，我现在的开发工作陷入停滞
因此我没有别的要求，只希望教我“如何彻底清除walle插件”，并恢复项目到集成之前的状态就行

**Comment by achellies** [comment]
要相信科学，如果不想用全部revert，代码都是开源的，哪里有对项目结构做成不可逆的改变？

**Comment by macouen** [comment]
6aG555uu5byA5rqQ77yM5L2/55So6Ieq5oS/77yM5Lia5Yqh5LiN57K+77yM5a6b6Iul5pm66Zqc44CC

**Comment by zyktojo** [comment]
已解决
已确认不是walle造成的问题，这个锅该高德地图背
高德地图上周四更新了最新版本之后，我从那以后安装的包就全都是白屏了
但是我经过三天申诉和发工单咨询之后，都得知了否定的答案，我不得不转回来问walle的大家
但是刚才！我回退了一下高德地图的依赖，让他依赖于旧版本jar包，而不是跟随在线的最新版本
再重新安装，看地图，一切都正常了

高德地图开发团队，自己挖的坑，官网没有任何提示，甚至官方技术咨询都否认新版本存在问题，真的很坑
