### ISSUE TITLE
walle如何支持productFlavors? 现在的需求是，不同渠道包，有不同的appname和appicon

### ISSUE THREAD

**Issue by EvanEvil** [Meituan-Dianping/walle#160]
首先非常感谢您选用Walle。

Walle还有很多不足，在已经关闭的issue中我们解决了很多问题，在提交新issue时，可以去已经[关闭的issue中寻求答案](https://github.com/Meituan-Dianping/walle/issues?q=is%3Aissue+is%3Aclosed)。

为了更好的帮助我们定位问题，请在提issue时携带尽可能多的日志或者说明。

**Comment by GavinCT** [comment]
channel是依据一个flavor衍生出来的。
请注意区分使用flavor 和channel。  
如果是一个flavor想搞多个channel的话，直接使用。
如果这个flavor只有一个channel，可以直接打一个channel进去。
怎么打，仔细看readme。里面都提了flavor

**Comment by LiuzxGeek** [comment]
我也觉得walle缺少自动配置logo和appname的机制

**Comment by GavinCT** [comment]
请注意看上面的回复

**Comment by lvshaoping** [comment]
那如果是多个flavor的话应该怎么设置walle根据不同的flavor执行不同的config.json文件
