### ISSUE TITLE
Error:Execution failed for task ':app:processDebugResources'. > com.android.ide.common.process.ProcessException: Failed to execute aapt

### ISSUE THREAD

**Issue by junchenChow** [Meituan-Dianping/walle#161]
在message里面出现了一个no such 的错误 但是打包并没有中断 这个有影响吗。
Error:Unable to open class file /Users/x/x/x-x/app/build/generated/source/r/debug/x/x/x/Manifest.java: No such file or directory

**Comment by GavinCT** [comment]
与walle无关
