### ISSUE TITLE
AndroidStudio3.0 使用插件时问题

### ISSUE THREAD

**Issue by vclub** [Meituan-Dianping/walle#162]
添加 apply plugin: 'walle' 插件后
编译时提示这个信息
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

因为编译时需要通过打印获取一些信息, 在跑task时每次第一句都是这个,信息处理比较麻烦

**Comment by HugoXie0527** [comment]
AndroidStudio3.0官方推荐使用implementation或者api替代compile，至于为什么，自己百度一下。

**Comment by vclub** [comment]
可能我没有描述清楚,我所有的库都是使用的implementation或api, 没有任何使用 compile的库,但是添加walle后 一直提示这个

**Comment by vclub** [comment]
我觉得是plugin这个里面build.gradle的配置导致的吧
