### ISSUE TITLE
使用configFile的时候，alias没有打印出来。

### ISSUE THREAD

**Issue by sjylxb** [Meituan-Dianping/walle#163]
已经在configFile中为每个渠道设置alias，但是我使用命令 gradle clean assembleReleasechannels -PchannelList=meituan的时候，对应meituan的alias没有打印出来。当我使用 gradle clean assembleReleasechannels 打包全部渠道包的时候alias显示正常。

**Comment by GavinCT** [comment]
注意看readme
> 使用上述-P参数后，本次打包channelFile/configFile配置将会失效，其他配置仍然有效。 -PchannelList,-PchannelFile, -PconfigFile三者不可同时使用。
