### ISSUE TITLE
后端服务器如何能获取apk包中的渠道信息？

### ISSUE THREAD

**Issue by huangjinhong** [Meituan-Dianping/walle#164]
做自己的更新发布的时候，请问后端服务器如何才能获取apk包中的渠道信息？

**Comment by GavinCT** [comment]
![image](https://user-images.githubusercontent.com/4016698/32762592-de9fc982-c8bf-11e7-96f3-e2c0cab2d29f.png)

**Comment by pecdew** [comment]
后台上传apk包 需要校验渠道信息 使用的语言是php 这时候如何解析apk的渠道信息呢？
