### ISSUE TITLE
我需要集成到PHP后台并提供分渠道打包的功能，请问要怎么做？

### ISSUE THREAD

**Issue by qq363685855** [Meituan-Dianping/walle#167]
我们运营总监要求，要集成到PHP后台提供分渠道打包的功能，集成到公司的OA里，方便大家操作。
请问这个插件可以改成支持PHP后台的吗？麻烦提供一下源码和思路，谢谢！

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/164#issuecomment-346259298 
语言问题请自行解决

**Comment by GavinCT** [comment]
另外还有 cli提供，有java环境没有语言障碍
https://github.com/Meituan-Dianping/walle/tree/master/walle-cli
