### ISSUE TITLE
channel file does not exist 无法打多渠道包

### ISSUE THREAD

**Issue by iMiracle** [Meituan-Dianping/walle#17]
使用最新的1.0.3 ，无法打多渠道包
输出包提示如下信息：
Removed unused resources: Binary resource data reduced from 4323KB to 4323KB: Removed 0%
:app:mergeReleaseJniLibFolders                               
:app:transformNative_libsWithMergeJniLibsForRelease                 
:app:packageRelease                 
:app:assembleRelease
:app:assembleReleaseV2SignatureSchemeChannel                 
channel file does not exist
APK Signature Scheme v2 Channel Maker takes about 0 milliseconds

BUILD SUCCESSFUL

Total time: 5 mins 17.994 secs
在build\outputs\apk目录下只有一个release包，无配置文件中多渠道的包
channel文件在android\app下

请问是什么原因导致channel文件找不到的？

**Comment by GavinCT** [comment]
你使用的指令发一下？ 
channel文件放置的位置和你指定的是否一致呢？ 注意相对路径   或者 你可以直接使用绝对路径

**Comment by GavinCT** [comment]
# chentong @ chentongs-MacBook-Pro in ~/Codes/Github/walle on git:develop o [16:50:49] 
$ ./gradlew clean :app:assembleDebug -PchannelFile=app/channel 

![image](https://cloud.githubusercontent.com/assets/4016698/22142339/dcad8fac-df30-11e6-8cf3-52fc17874b23.png)

或者 cd 到app下

# chentong @ chentongs-MacBook-Pro in ~/Codes/Github/walle/app on git:develop o [16:52:53] 
$ ./gradlew clean :app:assembleDebug -PchannelFile=channel

**Comment by iMiracle** [comment]
编译指令：
gradlew clean
gradlew assembleRelease -PchannelFile=channel
channel所在路径：
![seolb7u j wl h3bsrme w](https://cloud.githubusercontent.com/assets/8724128/22143875/9ac3ce52-df36-11e6-8ad8-0f6858e52f12.png)

**Comment by GavinCT** [comment]
注意看我写的那部分 你执行gradlew时不是在上一个层级执行的 否则应该是 
../gradlew clean :app:assembleDebug -PchannelFile=channel

**Comment by iMiracle** [comment]
抱歉，之前反馈的信息不全。
windows 10 环境， gradlew 版本 2.14.1
channel 文件所在路径：
![xwin65d3 a8y t8 plk 37](https://cloud.githubusercontent.com/assets/8724128/22147568/16cb6764-df44-11e6-9df5-931801662524.png)

在android studio下Terminal输出如下： 
![c jwz3 5r ws ztw2vg30](https://cloud.githubusercontent.com/assets/8724128/22147291/d3ba173c-df42-11e6-96d9-4227210357eb.png)

build完成后，如下：
![3 i11_cacgg g1sys nve](https://cloud.githubusercontent.com/assets/8724128/22147454/a34b4520-df43-11e6-8c0a-232de573e756.png)

还是提示channel file does not exist，路径和编译应该都没问题的。

**Comment by GavinCT** [comment]
你还是没看我说的那些东西啊。。。

**Comment by GavinCT** [comment]
对于你这个使用来说 如果你再android目录下
 ./gradlew clean :app:assembleDebug -PchannelFile=app/channel 
如果你进入到app目录下 
 ../gradlew clean :app:assembleDebug -PchannelFile=channel 

注意执行命令的地方和channel文件的相对路径

**Comment by iMiracle** [comment]
问题解决了，路径问题，抱歉之前没仔细看命令，tanks
例外提个小建议：多渠道打包的情况下，新建文件夹，所有的多渠道的apk放在一起，便于查看管理。 @ #

**Comment by JoxHero** [comment]
我也遇到了这个问题，注意注意注意，在AndroidStudio新建文本文件channel，不要带后缀
