### ISSUE TITLE
可以动态的配置AndroidManifest 吗？

### ISSUE THREAD

**Issue by LYC-Android** [Meituan-Dianping/walle#170]
我们的项目要求是在不同的渠道里面区别在于不同AndroidManifest中的<meta id="channeld" values="12345">大概类似这样，我需要怎么做

**Comment by dengyuhan** [comment]
[#74](https://github.com/Meituan-Dianping/walle/issues/74)

**Comment by GavinCT** [comment]
推荐把信息写到walle区域里吧
如果想改清单，还是使用flavor比较好。
注意区分flavor和walle channel
