### ISSUE TITLE
这个项目能和 AndResGuard 配合使用吗？

### ISSUE THREAD

**Issue by drakeet** [Meituan-Dianping/walle#173]
如题，请问 walle 可以修改依赖 task 吗？默认似乎是 assembleRelease，如果使用 AndResGuard，需要能够依赖 resguardRelease，不知道是否支持？
谢谢！

附：https://github.com/shwenzhang/AndResGuard

**Comment by achellies** [comment]
AndResGuard和Walle的Gradle插件都是要dependOn assembleRelease 的，而AndResGuard需要对APK进行修改，如果想配合使用，必须要保证Walle的task在AndResGuard的task之后执行。

目前有几种方式可以做到这种情况：
1. 通过修改插件的代码来改造插件，一种方式是修改Walle或AndResGuard的代码，可以通过 `RunAfter` 或 `dependsOn` 来指定task的执行顺序，另外一种是改造AndResGuard的插件代码，使用walle的Jar或者Gradle插件的代码，在AndResGuard执行完成后再处理
2. 通过apply plugin的顺序调整看是否能控制这2个task的执行时顺序，只要能保证walle的task在andresguard之后执行即可
