### ISSUE TITLE
Demo跑不通？打包时报错，是还有什么其他配置吗？

### ISSUE THREAD

**Issue by dreamfish797** [Meituan-Dianping/walle#174]
* What went wrong:
Execution failed for task ':app:assembleReleaseChannels'.
> Failed to parse template script (your template may contain an error or be trying to use expressions not currently supported): startup failed:
  SimpleTemplateScript1.groovy: 3: unexpected char: 0xFFFF @ line 3, column 40.
     /* Generated by SimpleTemplateEngine */
                                            ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 23.15 secs

**Comment by GavinCT** [comment]
按照提示加上--stacktrace试试

**Comment by ImportEffort** [comment]
@dreamfish797  这个问题如何解决的？我今天集成tinker后在用walle打包指令也出现了这个问题
