### ISSUE TITLE
能否设置打出来的渠道包的命名规则

### ISSUE THREAD

**Issue by ArtisanM** [Meituan-Dianping/walle#18]
目前后缀都是-channel    我想改成_channel或者其他的  能改吗

**Comment by GavinCT** [comment]
参考这个  https://github.com/Meituan-Dianping/walle/issues/3

**Comment by GavinCT** [comment]
如果仅仅是想改成下划线的 可以生成以后写个shell直接rename改掉就行了 如果想加一些东西的话 可以参考issue3里的最后一个回答

**Comment by ArtisanM** [comment]
好的谢谢
