### ISSUE TITLE
当打得渠道很多的时候会丢失一些渠道 并且有的渠道打出来是0kb

### ISSUE THREAD

**Issue by lhjandroid** [Meituan-Dianping/walle#181]
首先非常感谢您选用Walle。

Walle还有很多不足，在已经关闭的issue中我们解决了很多问题，在提交新issue时，可以去已经[关闭的issue中寻求答案](https://github.com/Meituan-Dianping/walle/issues?q=is%3Aissue+is%3Aclosed)。

为了更好的帮助我们定位问题，请在提issue时携带尽可能多的日志或者说明。

**Comment by achellies** [comment]
使用插件还是命令行？
如果能够复现，把过程中的日志信息发到这里吧

**Comment by lhjandroid** [comment]
用的命令行 在我的机器上是必现的 你自己也可以随机写500个渠道 来打包试试 命令行里没有错误信息

**Comment by lhjandroid** [comment]
java -jar walle-cli-all.jar batch -f chanal.txt test.apk d:\out 用的这个命令行打多个渠道包

**Comment by GavinCT** [comment]
提供下你的channel文本？ 目前所有用户并没有发生过类似问题

**Comment by lhjandroid** [comment]
发现问题了 渠道文件里有重复的渠道名导致好像少了一些渠道的问题 但是有的打出0kb的问题不指导是什么情况引起的

**Comment by GavinCT** [comment]
提供下你的channel文本？ 目前所有用户并没有发生过类似问题
