### ISSUE TITLE
使用walle打出渠道包后，再使用360加固，渠道编号失效~

### ISSUE THREAD

**Issue by iceyang1989** [Meituan-Dianping/walle#185]
目前，我的做法是先加固，然再去使用walle生成渠道包，渠道编号没有被擦除。不知道有没有更好的办法。

**Comment by achellies** [comment]
https://github.com/Meituan-Dianping/walle/wiki/360%E5%8A%A0%E5%9B%BA%E5%A4%B1%E6%95%88%EF%BC%9F
