### ISSUE TITLE
walle 根据不同的Flavors使用不同的config.json

### ISSUE THREAD

**Issue by lvshaoping** [Meituan-Dianping/walle#186]
在使用walle多渠道打包时，希望根据不同的包名读取不同的config设置，但是读取到的包名一直是默认的，而不是Flavors覆盖后的，怎样可以获取到被flavors覆盖后的最终包名呢

if(android.defaultConfig.manifestPlaceholders.app_pkgName ==A){
        configFile = new File("${project.getProjectDir()}/configA.json")  
    }else{
        configFile = new File("${project.getProjectDir()}/config.json")
    }

**Comment by achellies** [comment]
这个需求其实是需要针对不同的flavor能配置不同的config？在walle的闭包中是无法获取最终的包名的，能大概讲一下这个需要针对不同flavor配置不同的config的使用场景吗？我们看看是否有必要支持

**Comment by lvshaoping** [comment]
是的，根据不同的flavor能配置不同的config。
场景是：在使用一套代码打2种包名的包时，需要统计这两种包的下载量。因为市场的需求，渠道不能只用一种，需要根据不同包名设置为不同渠道，A包和B包在华为市场的渠道名称分明是A_huawei，B_huawei

**Comment by achellies** [comment]
好，我们考虑下怎么支持这种场景

**Comment by lvshaoping** [comment]
好的，谢谢

**Comment by achellies** [comment]
https://github.com/Meituan-Dianping/walle/pull/189

**Comment by achellies** [comment]
看下这个demo代码

**Comment by lvshaoping** [comment]
这个对channel的文件是有用的，但是对于有附加信息的config.json文件是不支持的

**Comment by achellies** [comment]
+afterEvaluate {
 +    project.android.applicationVariants.all { BaseVariant variant ->
 +        variant.assemble.doFirst {
 +            if (variant.applicationId.endsWith(".debug")) {
 +
 +                project.walle.channelFile = new File("${project.getProjectDir()}/channel_debug")
 +            }
 +        }
 +    }
 +} 

上面换成 configFile = new File("${project.getProjectDir()}/config.json") 也一样的啊

**Comment by lvshaoping** [comment]
可以了，之前project.walle.channelFile = new File("${project.getProjectDir()}/channel_debug") 只换了后面的文件，前面的channelFile没有换，现在可以了，多谢
