### ISSUE TITLE
Error:Plugin requires 'APK Signature Scheme v2 Enabled' for release.

### ISSUE THREAD

**Issue by GSpipi** [Meituan-Dianping/walle#188]
apply plugin: 'walle'
 
添加这个 plugin 后  报错 
Error:Plugin requires 'APK Signature Scheme v2 Enabled' for release.

**Comment by sangxb** [comment]
看下你的signingConfigs是不是加了禁用v2签名增强模式（ v2SigningEnabled false ），有的话注释掉即可
