### ISSUE TITLE
google play app signing的重新签名问题

### ISSUE THREAD

**Issue by hujiaweibujidao** [Meituan-Dianping/walle#190]
大家好，最近遇到个有点棘手的问题，问题大致如下：

1.我之前有个app在google play上发布了，并已经加入了 google play app signing，那个使用还没有使用walle打渠道包；

2.后来引入walle打渠道包，我发现打出来的包直接安装到手机上是可以看到正确的渠道号的，但是如果我将这个apk上传到google play上，然后在play商店下载下来的时候那个渠道号却没有了；

3.查了下原因，有两个重要点：

- walle有提到 **使用apksigner重新对Apk签名会导致渠道信息丢失，需要再次写入渠道信息**；

- 在google play console中将应用加入了google play app signing之后，google会对上传的apk进行密钥删除并重新签名的操作，并且加入之后就不能取消这个设置了，[对应文档](https://support.google.com/googleplay/android-developer/answer/7384423)

现在我希望能够依旧使用walle来打多渠道包，但是又能够在google play上继续发布新版本，还能从中正确读取渠道号怎么办呢？

大家有遇到类似问题的吗？在此求助下。

Any help is appreciated.

**Comment by achellies** [comment]
这个是因为google再次签名时会把apk signing block给干掉，walle这块没啥可以操作的了，不过我们可以让google play的渠道单独打包，添加个单独的flavor， 把渠道信息在代码里写死，或者放到其他文件里都行

**Comment by hujiaweibujidao** [comment]
@achellies 谢谢建议。
