### ISSUE TITLE
友盟的meta-data 怎么动态写入value

### ISSUE THREAD

**Issue by lvshtwl** [Meituan-Dianping/walle#191]
首先非常感谢您选用Walle。

Walle还有很多不足，在已经关闭的issue中我们解决了很多问题，在提交新issue时，可以去已经[关闭的issue中寻求答案](https://github.com/Meituan-Dianping/walle/issues?q=is%3Aissue+is%3Aclosed)。

为了更好的帮助我们定位问题，请在提issue时携带尽可能多的日志或者说明。

**Comment by achellies** [comment]
友盟的meta-data是在manifest里吧，你可以用manifestplaceholde来搞定，具体做法可以去google下，

如果想用walle的话可以用友盟的api动态设置meta－data，从walle的渠道信息里获取这个value，然后用api进行设置

**Comment by lvshtwl** [comment]
好的。谢谢
