### ISSUE TITLE
Error:Plugin requires 'APK Signature Scheme v2 Enabled' for release.

### ISSUE THREAD

**Issue by BinZhiLy** [Meituan-Dianping/walle#195]
首先非常感谢您选用Walle。

Walle还有很多不足，在已经关闭的issue中我们解决了很多问题，在提交新issue时，可以去已经[关闭的issue中寻求答案](https://github.com/Meituan-Dianping/walle/issues?q=is%3Aissue+is%3Aclosed)。

为了更好的帮助我们定位问题，请在提issue时携带尽可能多的日志或者说明。

**Comment by GavinCT** [comment]
注意学会在关闭的issue中寻求答案  https://github.com/Meituan-Dianping/walle/issues?q=is%3Aissue+is%3Aclosed 
也注意看提交模版中的提示。

**Comment by BinZhiLy** [comment]
thanks
