### ISSUE TITLE
Walle打包配合ARouter打包出现以下错误日志

### ISSUE THREAD

**Issue by wtt945482445** [Meituan-Dianping/walle#196]
> Task :app:compileReleaseJavaWithJavac
注: ARouter::Compiler >>> AutowiredProcessor init. <<<
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> InterceptorProcessor init. <<<
注: ARouter::Compiler The user has configuration the module name, it was [app]
注: ARouter::Compiler >>> RouteProcessor init. <<<
警告: 以下选项未被任何处理程序识别: '[moduleName]'

**Comment by achellies** [comment]
这个不是个警告信息？如果有失败，把整个完整的log附上

**Comment by wtt945482445** [comment]
解决了，是由于ARouter的混淆配置不清晰的问题
