### ISSUE TITLE
在build.gradle配置 apk的输出文件夹和文件名时，walle一整块都识别不了

### ISSUE THREAD

**Issue by ap0806109** [Meituan-Dianping/walle#197]
我主要是想修改输出文件的名字，加上walle这一块，就报错，不加的话可以把所有渠道的包都打出来
![image](https://user-images.githubusercontent.com/5742657/34926044-f569c7c2-f9e7-11e7-8167-16675223b7a0.png)

**Comment by achellies** [comment]
前面加apply plugin: walle了吗？

**Comment by ap0806109** [comment]
加了，现在解决了 是版本问题 我用1.0.4就可以了 谢谢哈
