### ISSUE TITLE
拿不到渠道信息

### ISSUE THREAD

**Issue by ArtisanM** [Meituan-Dianping/walle#199]
用jar包查看是有渠道信息的，但是在app里用Reader读取出来渠道信息是null，这是什么原因？该怎么排查

**Comment by achellies** [comment]
把app里读取渠道信息的代码和用jar包添加渠道的脚步贴一下

**Comment by ArtisanM** [comment]
String channel = WalleChannelReader.getChannel(this.getApplicationContext());
就是copy的demo代码，添加渠道是用你们的gradle插件添加的

**Comment by achellies** [comment]
把Apk上传一下？
