### ISSUE TITLE
输入gradlew clean assembleReleaseChannels后一直在下载东西，一直是百分之0

### ISSUE THREAD

**Issue by 541954852** [Meituan-Dianping/walle#200]

**Comment by 541954852** [comment]
![d5y n h q94n1pcc93e1z](https://user-images.githubusercontent.com/28174861/35321752-bc62fb96-0122-11e8-8a13-d1710f62472e.png)

**Comment by achellies** [comment]
网不好？用 --debug看看在下载什么？

**Comment by 541954852** [comment]
![f0mxb43 ew1 gitkhrt mf](https://user-images.githubusercontent.com/28174861/35322317-c928e5b4-0124-11e8-9dc3-a6736c6594ae.png)

**Comment by achellies** [comment]
看上面错误是你自身本地环境的问题，

Could not find tools.jar. Please check that D:\JDK\jre contains a valid JDK Installation.

**Comment by 541954852** [comment]
配置重装了好多次了，就是不行，一直报这个问题，不管是用AS再带的JDK还是自己下载的，都是这样。后来我把jdk目录下的东西整体复制到了jre下，然后重新编译就好了。。。不知道为什么，望解答 @ @achellies
