### ISSUE TITLE
使用walle打多渠道包后虽然下载了，但是在友盟的后台渠道里没有显示出来

### ISSUE THREAD

**Issue by 541954852** [Meituan-Dianping/walle#202]
友盟后台显示不出来渠道信息

**Comment by lvshtwl** [comment]
我也是，log看到能取到渠道信息，调用 UMConfigure.init方法，友盟后台就是显示不出

**Comment by 541954852** [comment]
@lvshtwl 你现在解决了吗？？

**Comment by lvshtwl** [comment]
还没有。。不知道为什么

**Comment by 541954852** [comment]
@lvshtwl 你再看一下友盟，的我这里渠道显示出来了，不过就是数量不对

**Comment by lvshtwl** [comment]
刚刚看了，还是没有。。。你也是调用UMConfigure.init（）方法，然后在友盟的后台看渠道分析？

**Comment by achellies** [comment]
排除法确认问题吧，看看walle从apk中获取的去到信息是否正确，调用友盟的接口是否成功带上了渠道信息

**Comment by willsame** [comment]
@lvshtwl  你的问题解决了么？我的也是一样的，是不是哪里设置错误了，如果知道的话，求告知，灰常感谢。
