### ISSUE TITLE
请问如果分发的apk包有校验该apk的Md5值，这种方式还有没有用

### ISSUE THREAD

**Issue by whhqhy** [Meituan-Dianping/walle#203]
有apk对整包校验MD5,这种情况下，分发多渠道包是不是会失败？

**Comment by achellies** [comment]
是的，如果对整包做校验，肯定是失败的

**Comment by achellies** [comment]
不光是walle，其他只要有一个基础包而再此基础上输出渠道包的方案都会存在这个问题，整包的MD5要和具体的渠道包关联
