### ISSUE TITLE
关于混淆的问题

### ISSUE THREAD

**Issue by caoshihong123456789** [Meituan-Dianping/walle#204]
用这种方式打出的包是否没有混淆；我用反编译工具反编译出来能看到所有activity文件；但是用gradle打包方式打出来的包，是看不到activity文件的；所以我想问，这样直接打包就可以了吗？还用不用加别的步骤加以混淆

**Comment by achellies** [comment]
`
    void applyTask(Project project) {
        project.afterEvaluate {
            project.android.applicationVariants.all { BaseVariant variant ->
                def variantName = variant.name.capitalize();

                if (!isV2SignatureSchemeEnabled(variant)) {
                    throw new ProjectConfigurationException("Plugin requires 'APK Signature Scheme v2 Enabled' for ${variant.name}.", null);
                }

                ChannelMaker channelMaker = project.tasks.create("assemble${variantName}Channels", ChannelMaker);
                channelMaker.targetProject = project;
                channelMaker.variant = variant;
                channelMaker.setup();

                channelMaker.dependsOn variant.assemble;
            }
        }
    }
`
直接看代码吧，用walle的插件大渠道包时是需要依赖assemble task的，和gradle打包方式没有什么区别
