### ISSUE TITLE
多渠道打包出来的apk，使talkingData无法统计到崩溃日志

### ISSUE THREAD

**Issue by caoshihong123456789** [Meituan-Dianping/walle#206]
我用的统计工具是talkingData，id 渠道配置也用的是动态配置的；使用walle之前，在androidmanifest里面配置的是可以统计到崩溃日志的，但是使用walle只有，就再也统计不到崩溃日志了；这个是walle的原因吗？

刚刚我做了一个统计；用gradle打出来的包都可以统计到崩溃；用walle打出的测试包也是可以统计到崩溃，但是用walle打出来的release包统计不到崩溃日志；

**Comment by achellies** [comment]
walle只是处理了zip格式里的一个区域，不会修改自身的代码逻辑
