### ISSUE TITLE
项目无法变异编译

### ISSUE THREAD

**Issue by Sing1** [Meituan-Dianping/walle#209]
Error:Plugin requires 'APK Signature Scheme v2 Enabled' for release.

**Comment by Sing1** [comment]
Error:(31, 0) Could not find method v2SigningEnabled() for arguments [true] on BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=debug, storeFile=C:\Users\pc\.android\debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=C:\Users\pc\.android\debug.keystore, v1SigningEnabled=true, v2SigningEnabled=true}, embedMicroApp=false, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.
<a href="openFile:E:\Work\yydy\app\build.gradle">Open File</a>

**Comment by achellies** [comment]
使用的Gradle Plugin和Gradle的版本是多少
