### ISSUE TITLE
执行gradlew clean assembleReleaseChannels 打包命令失败

### ISSUE THREAD

**Issue by xu283900277xiu** [Meituan-Dianping/walle#210]
大家好，请教一个问题，我在执行gradlew clean assembleReleaseChannels 这个命令打包失败，提示以下错误
Task 'assembleReleaseChannels' not found in root project 'XXX'. 大概意思是在我的项目中没有找到这个构建任务 ？？？

**Comment by achellies** [comment]
你的项目apply walle插件了吗？

**Comment by featureSapphire** [comment]
我的出现的也是这个问题，使用了apply walle

**Comment by yoonerloop** [comment]
我也遇到这样的问题：Parallel execution with configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleReleaseChannels' not found in root project 'ChannelPackage'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log outp
ut.

**Comment by EroneCui** [comment]
我也遇见了这个问题。我记得17年的时候用着还好好的，这个月刚想用发现项目里找不到assembleReleaseChannels了
