### ISSUE TITLE
按照说明的步骤无法生成apk,还需要额外安装NDK以及其他配置信息吗？

### ISSUE THREAD

**Issue by yoonerloop** [Meituan-Dianping/walle#214]
What went wrong:
A problem occurred configuring project ':app'.
> Plugin requires 'APK Signature Scheme v2 Enabled' for release.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by achellies** [comment]
开启v2签名即可
