### ISSUE TITLE
如何指定已使用360加固的apk进行渠道打包

### ISSUE THREAD

**Issue by magic0908** [Meituan-Dianping/walle#215]
你好，我最新打出来的release.apk，使用了360加固，也重新签名了，这个时候我应该怎么指定加固后的apk进行渠道打包？

**Comment by achellies** [comment]
https://github.com/Meituan-Dianping/walle/wiki/360%E5%8A%A0%E5%9B%BA%E5%A4%B1%E6%95%88%EF%BC%9F
