### ISSUE TITLE
gradlew clean assembleReleaseChannels 失败，请问walle不支持gradle 3.1.0吗？

### ISSUE THREAD

**Issue by hero0812** [Meituan-Dianping/walle#218]
如图所示，运行打包命令的时候，报了错误，gradle3.1.0
![5bbc9720-a67e-4da4-8e80-2acafd8657ce](https://user-images.githubusercontent.com/13467349/38716002-0ccfda46-3f11-11e8-8d68-6e0ce04003c1.png)

**Comment by k1988** [comment]
你点击那个链接看看能不能下载就明白这应该是GFW的问题。
