### ISSUE TITLE
gradlew clean assembleReleaseChannels 去生成渠道包出现错误

### ISSUE THREAD

**Issue by yacheng199306** [Meituan-Dianping/walle#219]
这是我的buildTypes
![image](https://user-images.githubusercontent.com/29671005/38916032-67f17e42-4318-11e8-8b2a-99c240b8304e.png)
如果我使用  gradlew clean assembleDebugChannels  去生成渠道包，是没有问题的。
如果我使用  gradlew clean assembleReleaseChannels 去生成渠道包，会报下面的问题：
![image](https://user-images.githubusercontent.com/29671005/38916266-3f807b56-4319-11e8-9383-6b5a6bfb48cf.png)
![image](https://user-images.githubusercontent.com/29671005/38916282-561db842-4319-11e8-8b7b-005e482eac54.png)
![image](https://user-images.githubusercontent.com/29671005/38916341-9804fa86-4319-11e8-8ac5-0088be75e65b.png)
![image](https://user-images.githubusercontent.com/29671005/38916400-d305e92e-4319-11e8-9fa3-2ca74873a01c.png)

**Comment by achellies** [comment]
看截图里的错误是proguard的报出来的呢

**Comment by yacheng199306** [comment]
嗯，我知道了。你们回答问题速度有点慢。
