### ISSUE TITLE
为什么只能用360加固，不能用乐固？360加固实在不敢恭维

### ISSUE THREAD

**Issue by chengfan2017** [Meituan-Dianping/walle#224]
首先非常感谢您选用Walle。

Walle还有很多不足，在已经关闭的issue中我们解决了很多问题，在提交新issue时，可以去已经[关闭的issue中寻求答案](https://github.com/Meituan-Dianping/walle/issues?q=is%3Aissue+is%3Aclosed)。

为了更好的帮助我们定位问题，请在提issue时携带尽可能多的日志或者说明。

**Comment by chengfan2017** [comment]
不同的账号竟然加固后的大小都不一样，360信不过

**Comment by achellies** [comment]
市面上的加固都可以用的，只是如果加固破坏了v2的签名，则需要重新签名的
