### ISSUE TITLE
walle 本地运行时如何获取渠道信息

### ISSUE THREAD

**Issue by ImportEffort** [Meituan-Dianping/walle#235]
查看了之前有提及的issues #201 ，但是还是不太明白在哪里配置，通过run app 运行app的时候，如何读取渠道信息？求指点

感觉是在run app 的时候没有进行渠道写入操作，但是项目中的一些初始化和接口请求需要携带渠道信息，有没有办法在run app 执行渠道写入的操作，使WalleChannelReader.getChannelInfo(this.getApplicationContext()); 不为空

**Comment by xlc1540697096** [comment]
1. 在as中开发时，时不时需要点击右上角的运行按钮，此时运行的apk是没有渠道信息的；
2. 这个时候没有渠道信息是合理，且正常的，因为app还处于开发阶段；渠道数据是app开发的收尾工作；
3. 可以尝试下面这个：
![](http://hololenspic.oss-cn-shenzhen.aliyuncs.com/18-6-22/12066843.jpg)
这里有debug， release，但这个和你说的没有关系；debug用的自己生成的debug签名打的，然后打上渠道包，release同理；

**Comment by ImportEffort** [comment]
@xlc1540697096  谢谢回答，由于项目重的某些接口需要渠道名称（我也不知道当时为什么这么强制处理），所以我在debug（run app）的模式下，手动给渠道信息赋予了默认值的处理。暂时能解决问题。
