### ISSUE TITLE
无法修改打包生成的apk名字

### ISSUE THREAD

**Issue by Ruijiao** [Meituan-Dianping/walle#24]
productFlavors {
      ceshi {}
  }
通过这种方式指定渠道名
再结合这个命令 gradlew clean assembleRelease
问题：
可以打出包，但是获取不到渠道名，为空

**Comment by GavinCT** [comment]
请注意正确区分flavor和channel的概念。 
walle只有当加入-Pchannel参数的时候才会工作  如果你想要flavor+channel的效果：
 gradlew clean assembleCeshiRelease -PchannelList=ceshi
