### ISSUE TITLE
请问walle可以实现差异化打包吗？

### ISSUE THREAD

**Issue by ZhongHaoHero666** [Meituan-Dianping/walle#246]
查了issus和网上其他的思路，但并没有很好地差异化打包解决方案。
需求是：根据不同渠道名称，动态修改应用程序的applicationId和sourcesets，之前是通过flavor做的，现在需要加上资源文件混淆，请问walle有没有好的解决方案、。

**Comment by xlc1540697096** [comment]
你继续使用flavor方式，
最后用java命令为已经生成的apk，打入渠道信息

**Comment by ZhongHaoHero666** [comment]
多谢楼上的回答，相对于gradle  插件来说，使用jar包的方法会更加个性化。
