### ISSUE TITLE
加固后手动进行v2签名的问题

### ISSUE THREAD

**Issue by peerless2012** [Meituan-Dianping/walle#25]
选择360加固后需要重签名，360自带工具是v1签名，手动用apksigner进行签名的话报错，如下：
    
    D:\develop\git\keystore>apksigner sign --ks D:\develop\git\keystore\simple_test1
    .    jks D:\develop\git\keystore\app-official-release-360cn.encrypted.apk
    Keystore password for signer #1:
    Failed to load signer "signer #1"
    java.io.IOException: Failed to obtain key with alias "test1" from D:\develop\git
    \keystore\simple_test1.jks. Wrong password?
            at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCer
    tsFromKeyStore(ApkSignerTool.java:690)
            at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCer
    ts(ApkSignerTool.java:555)
            at com.android.apksigner.ApkSignerTool$SignerParams.access$200(ApkSigner
    Tool.java:509)
            at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:215)
            at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
    Caused by: java.security.UnrecoverableKeyException: Cannot recover key
            at sun.security.provider.KeyProtector.recover(KeyProtector.java:328)
            at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:146
    )
            at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java
    :56)
            at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegato
    r.java:96)
            at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKey
    Store.java:70)
            at java.security.KeyStore.getKey(KeyStore.java:1023)
            at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCer
    tsFromKeyStore(ApkSignerTool.java:663)
            ... 4 more

但是使用调试签名进行v2签名是可以的，获取v2签名信息如下：
```
D:\develop\git\keystore>java -jar D:\develop\git\keystore\CheckAndroidV2Signatur
e.jar D:\develop\git\keystore\app-official-release-360cn.encrypted.apk
{"ret":0,"msg":"ok","isV2":true,"isV2OK":true} 
```

通过Keytool命令，分析两个签名的内容，只找到一处不同：

* 可以通过的debug的签名用的是签名算法名称: SHA1withRSA  版本: 3 
* 无法签名，提示错误的签名用的是签名算法是：签名算法名称: SHA256withRSA   版本: 3

另：报错的签名是AS进行创建的。

附两个keystore的keytool信息：

```

D:\develop\git\keystore>keytool -list -v -keystore D:\develop\git\keystore\simpl
e_test1.jks
输入密钥库口令:

密钥库类型: JKS
密钥库提供方: SUN

您的密钥库包含 1 个条目

别名: test1
创建日期: 2017-2-8
条目类型: PrivateKeyEntry
证书链长度: 1
证书[1]:
所有者: CN=t, OU=t, O=t, L=t, ST=t, C=86
发布者: CN=t, OU=t, O=t, L=t, ST=t, C=86
序列号: 1b12f74d
有效期开始日期: Wed Feb 08 10:35:46 CST 2017, 截止日期: Sun Feb 02 10:35:46 CST
2042
证书指纹:
         MD5: 76:C0:09:30:FC:7B:A2:6A:57:8F:5B:E0:4F:A4:83:A5
         SHA1: 29:8D:00:CC:3A:74:AE:F8:4C:3F:87:C4:04:86:A0:60:65:A8:1B:37
         SHA256: FC:2A:5A:CC:E3:6E:9F:70:15:DD:01:99:0A:EB:16:D2:86:E5:E4:7F:A1:
92:56:32:A4:9B:F5:1D:24:A1:46:3D
         签名算法名称: SHA256withRSA
         版本: 3

扩展:

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 42 9D DE 94 66 61 B1 17   0F D6 1B 54 B8 C7 38 D9  B...fa.....T..8.
0010: 3B E7 56 20                                        ;.V
]
]



*******************************************
*******************************************

D:\develop\git\keystore>keytool -list -v -keystore C:\Users\Administrator\.andro
id\debug.keystore
输入密钥库口令:

密钥库类型: JKS
密钥库提供方: SUN

您的密钥库包含 1 个条目

别名: androiddebugkey
创建日期: 2016-9-5
条目类型: PrivateKeyEntry
证书链长度: 1
证书[1]:
所有者: C=US, O=Android, CN=Android Debug
发布者: C=US, O=Android, CN=Android Debug
序列号: 1
有效期开始日期: Mon Sep 05 14:05:29 CST 2016, 截止日期: Wed Aug 29 14:05:29 CST
2046
证书指纹:
         MD5: 3F:2A:E7:EA:71:D2:EB:DF:EE:BE:75:60:1F:3C:72:18
         SHA1: 5F:78:1B:6C:94:DB:0C:9C:1A:8D:C0:EE:B6:23:A8:F1:82:FB:71:8C
         SHA256: 01:5B:88:57:01:71:6C:E9:3A:24:39:DF:C2:ED:DB:BC:3C:03:B7:FD:73:
C5:09:59:F0:3F:2C:4D:32:72:4C:82
         签名算法名称: SHA1withRSA
         版本: 1


*******************************************
*******************************************
```

**Comment by achellies** [comment]
Failed to load signer "signer #1"
java.io.IOException: Failed to obtain key with alias "test1" from D:\develop\git
\keystore\simple_test1.jks. Wrong password?

**Comment by peerless2012** [comment]
密码没问题，自己手动输入和拷贝过去都试了

**Comment by achellies** [comment]
是使用的buildtools 25下的apksigner.jar吗

**Comment by peerless2012** [comment]
对的，用的是buildtools 25.0.1中的apksigner.jar。
已经找到原因了，**别名的密码跟存储密码必须一致**。
瓦力又满血复活了，建议把这个说明加到README中，方便其他人绕坑。

参考链接：
[Ant fails to build signed apk after updating to android v20](http://stackoverflow.com/questions/11625262/ant-fails-to-build-signed-apk-after-updating-to-android-v20)
[Android keystore stopped working](http://stackoverflow.com/questions/13535424/android-keystore-stopped-working)

**Comment by wswenyue** [comment]
https://github.com/wswenyue/channelHelper
可以试试这个。支持360渠道

**Comment by wuwenbo6** [comment]
@wswenyue 你这个不好用啊，老是优化出错...
