### ISSUE TITLE
Android9.0安装失败

### ISSUE THREAD

**Issue by feitengbing2014** [Meituan-Dianping/walle#256]
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1019286578.tmp/base.apk using
 APK Signature Scheme v3: Size of APK Signing Block is not a multiple of 4096: 4128]

**Comment by yehengzhishang** [comment]
昨天发现这个问题了，but.还没有找到原因。偷偷的把美团app与美团wm两个app下载下来了，是能安装的。也发现有渠道的。这就很尴尬了。又重复试了几次，发现一个好玩的情况 ，通过 Android Studio build -> generate signed APK 打出的apk. 通过walle-cli-all.jar 打入渠道，是没问题的。 如果通过gradlew 的命令打出未签名包 然后用sdk 里面的zipalign 对齐 apksigner签名加密后。包是安装的，如果这个包通过 walle-cli-all.jar 打入渠道，然后安装，就会报错。还没查到为什么。

Android stuiod 版本 3.2 
项目 gradle 4.4 
android gradle 3.1.4
zipalign 与apksinger 试过两个版本 28.0.2 28.0.3 
walle-cli-all.jar 1.1.6

ps: 对于APK Signature Scheme v3 这个是不是新的签名方式还有待研究 这个相关内容确实在apksigner  最近3个月提交上看到了。还没细研究

希望大神指点下

**Comment by yehengzhishang** [comment]
去墙外搜索下了，APK Signature Scheme v3 还真是新的签名方式。
官方指路 https://source.android.com/security/apksigning/v3 
原谅我英文渣渣，没看懂。但是我大胆的猜测。应该是walle 跟v3签名冲突了。看介绍的时候，发现如果没有v3 签名，就去校验v2 签名，问题了来了，为啥我的包会有v3 签名呢？ 应该是zipalign spksinger 版本太高关。。。 于是，我重新gradlew 生成包 拿了27 版本的build-tools，对齐，签名 打渠道，安装 success... 至于android studio为啥能成功，很大概率上，是当前项目build-tools没有那么高。生成的包并没有v3 签名。为啥冲突，还有待研究，不过这种对于walle来说，是个隐藏bug

**Comment by yrom** [comment]
walle 应该还没有支持 v3 签名
