### ISSUE TITLE
jar 的下载地址在哪

### ISSUE THREAD

**Issue by 3c** [Meituan-Dianping/walle#257]
说是在release里，没看到

**Comment by PWJiang** [comment]
I also encountered the same problem

**Comment by 3c** [comment]
> I also encountered the same problem

自己build一份吧， clone工程后导入android studio 在 cli项目里有一个 shadowjar ，执行下会生成jar

**Comment by 3c** [comment]
试一下上传zip

[walle-cli-all.jar.zip](https://github.com/Meituan-Dianping/walle/files/2431319/walle-cli-all.jar.zip)

**Comment by GavinCT** [comment]
release中已经重新开放，之前仓库调整丢失了
