### ISSUE TITLE
打出来的apk命名规范怎么以渠道名命名？

### ISSUE THREAD

**Issue by Ruijiao** [Meituan-Dianping/walle#26]
打出来的apk命名规范怎么以渠道名命名？

**Comment by achellies** [comment]
命名规范参考 #3

**Comment by Ruijiao** [comment]
看过了，不知道如何获取当前的打的渠道名？

**Comment by GavinCT** [comment]
？？  解释下你的问题？
如果你打出一个apk 然后用walle签名 渠道都在后面带着啊

**Comment by GavinCT** [comment]
你是要把flavor的名字也加上么？

**Comment by Ruijiao** [comment]
例如我要打“百度”渠道，我需要打出来的apk名字就是baidu.apk

**Comment by GavinCT** [comment]
默认是app-release-baidu.apk 这种 
如果你只想要baidu的话 可以写个shell脚本处理下就完了  所有file rename一下就好了

**Comment by Ruijiao** [comment]
没办法做到打包的时候就弄好是么？例如像#3提到的，在这个里面进行处理

**Comment by achellies** [comment]
目前还不行，后面可能考虑增加个自定义名称功能

**Comment by GavinCT** [comment]
默认会加 -baidu 这种 你这里的需求是只要baidu.apk  这个 - 去不掉的
很少见你这种需求 现在不支持的
你可以写shell把最后一个-之前的部分都replace掉

**Comment by Ruijiao** [comment]
还一个问题，根据每个渠道替换不同的欢迎图可以做到么？
sourceSets{
        main {
            res.srcDirs = ['src\\main\\res','src\\main\\res_normal']
            jniLibs.srcDirs=['libs']
        }
        baidu{
            res.srcDirs = ['src\\main\\res','src\\main\\res_baidu']
        }
}
这是之前通过不同渠道读取不同文件夹做到的

**Comment by achellies** [comment]
这个如果用walle有点怪，使用flavor重新打包最好，或者通过apktool回编译，如果非用walle也可以但有些trick，欢迎图片都要编译在apk中，在channelinfo中指明用那张图，欢迎页通过获取channelinfo中的图片再去加载对应的图

**Comment by Ruijiao** [comment]
明白了，万分感谢
