### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/meituan/android/walle/f

### ISSUE THREAD

**Issue by longeleven** [Meituan-Dianping/walle#270]
实用V2打包的时候 在android 9.0上闪退

**Comment by liufsd** [comment]
编译版本是多少？ 28 还是 26 ？ @longeleven

**Comment by longeleven** [comment]
compileSdkVersion: 26,
            targetSdkVersion : 25,
            minSdkVersion    : 15,
            buildToolsVersion: "26.0.2",

**Comment by liufsd** [comment]
我targetSdkVersion 26 好像没遇到这个问题。  有demo可以必现么？

**Comment by longeleven** [comment]
华为mate10 手机系统升级之前可以正常安装运行 手机系统升级到9.0 安装之后点击应用闪退 抓的log就是标题里的那个

**Comment by longeleven** [comment]
我试试修改成targetSdkVersion 26

**Comment by longeleven** [comment]
好像和targetSdkVersion 这个配置没有关系 改成26 还是闪退

**Comment by longeleven** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/bugly/crashreport/CrashReport$UserStrategy; 

错误信息变了

**Comment by liufsd** [comment]
方便把apk给我下我么？

**Comment by liufsd** [comment]
@longeleven 我这里有华为mate10 但是是8.0的， 你是怎么升级到9.0系统的呢？
其次听下来，感觉和walle没有关系，你引入了什么其他的第三方dex处理相关的库么？ 比如热修复，dex分包之类的？

**Comment by longeleven** [comment]
热修复的tinker
