### ISSUE TITLE
阿里安全-诺亚云查杀报毒

### ISSUE THREAD

**Issue by lgengsy** [Meituan-Dianping/walle#273]
最近刚换成这种打包的方式，通过渠道上传的时候被报毒了，排查了好多种情况，最后定位到，用工具打包传上去会被报毒，不用工具打包直接传上去正常。
![image](https://user-images.githubusercontent.com/3983443/50534383-c626f880-0b76-11e9-8874-c0168bc8d256.png)

**Comment by liufsd** [comment]
是哪个渠道？。。？

**Comment by lgengsy** [comment]
pp助手这个渠道，只是提示这个问题，没有给出具体的什么病毒。

**Comment by liufsd** [comment]
他们的扫描是怎么验证的？ 有单独验证方式么？
比如给他们某一个apk，他们给个反馈。

**Comment by lgengsy** [comment]
谢谢，今天解决了，不是打包的问题，我们好几个媒体渠道包。当时只验证了一个（不用打包工具打就正常，用打包工具打就报毒）。其他的后来验证了下不是因为打包工具的问题，经过两天的沟通最后确定是媒体自己的问题😓。这个问题可以关闭了 。。非常感谢。
