### ISSUE TITLE
华为应用市场被当成病毒

### ISSUE THREAD

**Issue by zhangjianliang110** [Meituan-Dianping/walle#274]
华为市场审核被拒，提示由病毒
"a variant of Android/DataCollector.Utilcode.A" virus

**Comment by liufsd** [comment]
@zhangjianliang110  https://github.com/Meituan-Dianping/walle/issues/273
是否类似的原因呢？ 
具体是怎么操作的？

**Comment by zhangjianliang110** [comment]
#273的意思是平台的bug吗？华为应用市场把这当病毒，如果人家就不改咋办？有没解决方案？求美团大神指点。

**Comment by liufsd** [comment]
@zhangjianliang110  我不是美团的。。。
他那个说是媒体的问题，apk本身没问题的，你也可以尝试沟通一下看看。

**Comment by rgdzh1** [comment]
“1.你的应用检测含有病毒a variant of Android/DataCollector.Utilcode.A，”
我上传华为市场的时候也碰到这个问题了，求助~

**Comment by leielyq** [comment]
有人解决这个问题吗，我也遇到了，有点头疼，端午节都不能好好睡了

**Comment by zhangjianliang110** [comment]
解决了，跟人家walle没关系。我这边是因为项目中引用了blankj库，并且这个库的代码没有混淆，这个库里获取的很多设备信息属于隐私信息，国外有的杀毒软件会当成病毒。
解决方法，要么把这个库去掉，要么把库代码混淆。

**Comment by zhangjianliang110** [comment]
> 有人解决这个问题吗，我也遇到了，有点头疼，端午节都不能好好睡了

解决了，跟人家walle没关系。我这边是因为项目中引用了blankj库，并且这个库的代码没有混淆，这个库里获取的很多设备信息属于隐私信息，国外有的杀毒软件会当成病毒。
解决方法，要么把这个库去掉，要么把库代码混淆。

**Comment by zhangjianliang110** [comment]
看看你项目里有没有引用blankj这个库，我这边是这个库没有混淆，国外有的杀毒软件会报病毒。把这个库代码混淆就好了。




------------------ 原始邮件 ------------------
发件人: "杨"<notifications@github.com>; 
发送时间: 2019年6月7日(星期五) 下午4:33
收件人: "Meituan-Dianping/walle"<walle@noreply.github.com>; 
抄送: "张建良"<854977023@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [Meituan-Dianping/walle] 华为应用市场被当成病毒 (#274)




有人解决这个问题吗，我也遇到了，有点头疼，端午节都不能好好睡了

**Comment by leielyq** [comment]
> 看看你项目里有没有引用blankj这个库，我这边是这个库没有混淆，国外有的杀毒软件会报病毒。把这个库代码混淆就好了。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "杨"<notifications@github.com>; 发送时间: 2019年6月7日(星期五) 下午4:33 收件人: "Meituan-Dianping/walle"<walle@noreply.github.com>; 抄送: "张建良"<854977023@qq.com>; "Mention"<mention@noreply.github.com>; 主题: Re: [Meituan-Dianping/walle] 华为应用市场被当成病毒 (#274) 有人解决这个问题吗，我也遇到了，有点头疼，端午节都不能好好睡了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

谢谢谢，端午节快乐
