### ISSUE TITLE
输出的apk如何自定义文件名格式？比如{app}-{channel}-{version}.{ext}

### ISSUE THREAD

**Issue by czy1121** [Meituan-Dianping/walle#3]

**Comment by GavinCT** [comment]
考虑到自定义需求各种各样，我们并没有在plugin里提供模版。plugin只针对简单场景   
可以写个shell脚本利用[walle-cli](https://github.com/Meituan-Dianping/walle/blob/master/walle-cli/README.md)进行自定义    
例如你提到这个需求，可以有两个方案：
1. 利用plugin生成，然后写个shell把批量生成的apk改成你需要的名字。因为app和channel本身plugin都有，version对于一个版本来说也是固定的，很方便写出来。    
2. 直接利用cli。shell获取输入市场列表，针对apk使用cli单个打包的方式，加上你output指定上你输出的信息，然后for循环继续。

**Comment by achellies** [comment]
android {
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.outputFile = new File(
                    output.outputFile.parent,
                    output.outputFile.name.replace(".apk", "-${variant.versionName}.apk"))
        }
    }
}
可以配置{app}-{version}.apk,插件默认是在尾部加channel，这样配置后输出文件为 {app}-{version}-{channel}.apk

**Comment by Ruijiao** [comment]
渠道名的命名规范怎么以渠道名命名？
