### ISSUE TITLE
channel file does not exist

### ISSUE THREAD

**Issue by ccclll1990** [Meituan-Dianping/walle#30]
walle 项目直接checkout下来，在AS的Terminal执行 ./gradlew clean assembleRelease -PchannelFile=channel  渠道包没有打出来
![image](https://cloud.githubusercontent.com/assets/3463511/22872247/9ee3a88a-f1f2-11e6-9c5a-bb98df471dd1.png)

channel文件
![image](https://cloud.githubusercontent.com/assets/3463511/22872282/ee30d200-f1f2-11e6-9d3b-59b35a0702a5.png)

**Comment by fantasyado** [comment]
怎么解决的呢 我也遇到这个问题了

**Comment by LuoboDcom** [comment]
你们这个应该是路径不对
