### ISSUE TITLE
Could not find method walle() for arguments 

### ISSUE THREAD

**Issue by SharerMax** [Meituan-Dianping/walle#32]
Error:(95, 0) Could not find method walle() for arguments [build_1xpnhc3ozz0wtrcpdgdc37t1j$_run_closure2@28c2c774] on project ':app' of type org.gradle.api.Project.

walle plugin:1.0.3
gradle  version：3.3
Android Studio：2.2.3
OS：WIndows 10 X64

**Comment by achellies** [comment]
walle plugin1.0.4版本才解决了自定义输出目录和文件名，详见 #28 #29 ,需要等1.0.4版本发布后才能使用

**Comment by SharerMax** [comment]
thanks
