### ISSUE TITLE
迁移AndroidX后读取渠道号失败。

### ISSUE THREAD

**Issue by Rocketer2018** [Meituan-Dianping/walle#320]
迁移AndroidX后，出现读取渠道号失败。
不知晓是否是AndroidX混淆的问题。希望给出AndroidX的混淆方案。

**Comment by gongshoudao** [comment]
跟AndroidX没关系吧

**Comment by Rocketer2018** [comment]
> 跟AndroidX没关系吧

核实了，确实与AndroidX无关，google play 的问题。提交到Google Play之后，Google Play会抹掉你的渠道号。有同样问题的小伙伴们可以参考一下。
