### ISSUE TITLE
重新打包了walle-cli，希望官方更新有问题的1.6.0

### ISSUE THREAD

**Issue by itgowo** [Meituan-Dianping/walle#326]
除了增加了log外没改源码，（walle代码）解决Android V3签名校验问题，不知道什么原因release包1.6.0有问题，望官方更新，我打包的项目  https://github.com/itgowo/walle-cli  ，下载地址：https://github.com/itgowo/walle-cli/blob/master/walle-cli-1.6.1.jar，以上为临时方案，以walle官方为准

**Comment by sailor-deng** [comment]
> 除了增加了log外没改源码，（walle代码）解决Android V3签名校验问题，不知道什么原因release包1.6.0有问题，望官方更新，我打包的项目 https://github.com/itgowo/walle-cli ，下载地址：[https://github.com/itgowo/walle-cli/blob/master/walle-cli-1.6.1.jar，以上为临时方案，以walle官方为准](https://github.com/itgowo/walle-cli/blob/master/walle-cli-1.6.1.jar%EF%BC%8C%E4%BB%A5%E4%B8%8A%E4%B8%BA%E4%B8%B4%E6%97%B6%E6%96%B9%E6%A1%88%EF%BC%8C%E4%BB%A5walle%E5%AE%98%E6%96%B9%E4%B8%BA%E5%87%86)

感谢您的反馈，已更新到 1.1.7
