### ISSUE TITLE
Gradle4.0.0打出来的包安装失败：INSTALL_PARSE_FAILED_NO_CERTIFICATES

### ISSUE THREAD

**Issue by wenzhihao123** [Meituan-Dianping/walle#331]
### Gradle4.0.0打包安装报错
Android Studio版本：4.0
Gradle编译版本： 4.0.0
Gradle版本：distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
v2签名已开启：v2SigningEnabled true

打包命令：
```
./gradlew clean assembleReleaseChannels -PchannelList=xiaomi

```

打完包安装报错异常信息：
```
 Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from 
/data/app/vmdl591372221.tmp/base.apk using APK Signature Scheme v2: Size of APK Signing 
Block is not a multiple of 4096: 4128]
```
### 1.降到Gradle3.2.1 打包后正常安装
Gradle编译版本 3.2.1
Gradle版本：distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip

### 2.打包后的apk对齐、签名处理
需要下载 [walle-cli-all.jar](https://github.com/Meituan-Dianping/walle/issues/264) 
- 先进行对齐操作 ：$ANDROID_HOME/build-tools/26.0.2/zipalign -v 4 打的包.apk 新的包.apk
- V2签名工具再次签名新的Apk：$ANDROID_HOME/build-tools/26.0.2/apksigner sign --ks xxx.jks 新的包.apk
- 用walle-cli-all.jar写入渠道信息：java -jar walle-cli-all.jar put -c (渠道名，如：xiaomi) 新的包.apk

- 显示下是否写入渠道成功：java -jar walle-cli-all.jar show 新的包_渠道名.apk

降级Gradle只是能临时解决，长久来看还是希望能支持一下Gradle4.0.0~

**Comment by XuQK** [comment]
表示使用https://github.com/newdive/walle-python这个脚本打出来的包没有任何问题
Android Studio4.0
Gradle4.0.0
compileSdkVersion 29

**Comment by scsfwgy** [comment]
一直不升级也不是个办法，又是一个KPI项目，两年没更新了？

**Comment by scsfwgy** [comment]
目前以下配置可正常使用

distributionUrl=https://services.gradle.org/distributions/gradle-5.1.1-all.zip
classpath 'com.android.tools.build:gradle:3.4.1'

**Comment by marren06** [comment]
作者您好：
        啥时候适配Gradle 4.0.0啊？

**Comment by TSsimeon** [comment]
真的不更新了吗。难受！

**Comment by yousiwu111** [comment]
发现打测试包没问题，正式包会出现安装包解析失败

**Comment by marren06** [comment]
@yousiwu111 不都是这个问题啊    正式包安装  老提示解析失败不能安装

**Comment by yousiwu111** [comment]
@yousiwu111 debuggable true 这么设置目前没问题

**Comment by marren06** [comment]
release 打包模式下设置debuggable true ？？

**Comment by marren06** [comment]
@yousiwu111 release 打包模式下设置debuggable true ？？

**Comment by yousiwu111** [comment]
@marren06  是的

**Comment by Semenry** [comment]
遇到同样的问题
打包模式下设置debuggable true ？？这个怎么操作？

**Comment by marren06** [comment]
@scsfwgy 降gradle处理保险点  。
就是gradle配置信息里面 release 签名信息里面debuggable属性  设置true

**Comment by marren06** [comment]
@scsfwgy 降gradle处理保险点  。
就是gradle配置信息里面 release 签名信息里面debuggable属性  设置true

**Comment by scsfwgy** [comment]
> @scsfwgy 降gradle处理保险点 。
> 就是gradle配置信息里面 release 签名信息里面debuggable属性 设置true

不是解决之道，还是要升级的。上线debuggable打开会有问题的

**Comment by sailor-deng** [comment]
> ### Gradle4.0.0打包安装报错
> Android Studio版本：4.0
> Gradle编译版本： 4.0.0
> Gradle版本：distributionUrl=https://services.gradle.org/distributions/gradle-6.1.1-all.zip
> v2签名已开启：v2SigningEnabled true
> 
> 打包命令：
> 
> ```
> ./gradlew clean assembleReleaseChannels -PchannelList=xiaomi
> ```
> 
> 打完包安装报错异常信息：
> 
> ```
>  Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from 
> /data/app/vmdl591372221.tmp/base.apk using APK Signature Scheme v2: Size of APK Signing 
> Block is not a multiple of 4096: 4128]
> ```
> 
> ## 解决办法：
> ### 1.降到Gradle3.2.1 打包后正常安装
> Gradle编译版本 3.2.1
> Gradle版本：distributionUrl=https://services.gradle.org/distributions/gradle-5.4.1-all.zip
> 
> ### 2.打包后的apk对齐、签名处理
> 需要下载 [walle-cli-all.jar](https://github.com/Meituan-Dianping/walle/issues/264)
> 
> * 先进行对齐操作 ：$ANDROID_HOME/build-tools/26.0.2/zipalign -v 4 打的包.apk 新的包.apk
> * V2签名工具再次签名新的Apk：$ANDROID_HOME/build-tools/26.0.2/apksigner sign --ks xxx.jks 新的包.apk
> * 用walle-cli-all.jar写入渠道信息：java -jar walle-cli-all.jar put -c (渠道名，如：xiaomi) 新的包.apk
> * 显示下是否写入渠道成功：java -jar walle-cli-all.jar show 新的包_渠道名.apk
> 
> 降级Gradle只是能临时解决，长久来看还是希望能支持一下Gradle4.0.0~

感谢您的反馈，请使用 v1.1.7 版本，已修复该问题

**Comment by kaitian521** [comment]
辛苦了大佬们

**Comment by wenzhihao123** [comment]
@sailor-deng  walle V1.1.7 和 Gradle 4.0.0，打完包可以正常安装了，给大佬递咖啡☕

**Comment by Corey-Wang** [comment]
> > ### Gradle4.0.0打包安装报错
> > Android Studio版本：4.0
> > Gradle编译版本： 4.0.0
> > Gradle版本：distributionUrl=https://services.gradle.org/distributions/gradle-6.1.1-all.zip
> > v2签名已开启：v2SigningEnabled true
> > 打包命令：
> > ```
> > ./gradlew clean assembleReleaseChannels -PchannelList=xiaomi
> > ```
> > 
> > 
> > 打完包安装报错异常信息：
> > ```
> >  Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from 
> > /data/app/vmdl591372221.tmp/base.apk using APK Signature Scheme v2: Size of APK Signing 
> > Block is not a multiple of 4096: 4128]
> > ```
> > 
> > 
> > ## 解决办法：
> > ### 1.降到Gradle3.2.1 打包后正常安装
> > Gradle编译版本 3.2.1
> > Gradle版本：distributionUrl=https://services.gradle.org/distributions/gradle-5.4.1-all.zip
> > ### 2.打包后的apk对齐、签名处理
> > 需要下载 [walle-cli-all.jar](https://github.com/Meituan-Dianping/walle/issues/264)
> > 
> > * 先进行对齐操作 ：$ANDROID_HOME/build-tools/26.0.2/zipalign -v 4 打的包.apk 新的包.apk
> > * V2签名工具再次签名新的Apk：$ANDROID_HOME/build-tools/26.0.2/apksigner sign --ks xxx.jks 新的包.apk
> > * 用walle-cli-all.jar写入渠道信息：java -jar walle-cli-all.jar put -c (渠道名，如：xiaomi) 新的包.apk
> > * 显示下是否写入渠道成功：java -jar walle-cli-all.jar show 新的包_渠道名.apk
> > 
> > 降级Gradle只是能临时解决，长久来看还是希望能支持一下Gradle4.0.0~
> 
> 感谢您的反馈，请使用 v1.1.7 版本，已修复该问题

请问这个问题是怎么修复的呢，看master commit并没有发现修改代码。谢谢

**Comment by LBCross** [comment]
> > ### Gradle4.0.0打包安装报错
> > Android Studio版本：4.0
> > Gradle编译版本： 4.0.0
> > Gradle版本：distributionUrl=https://services.gradle.org/distributions/gradle-6.1.1-all.zip
> > v2签名已开启：v2SigningEnabled true
> > 打包命令：
> > ```
> > ./gradlew clean assembleReleaseChannels -PchannelList=xiaomi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 打完包安装报错异常信息：
> > ```
> >  Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from 
> > /data/app/vmdl591372221.tmp/base.apk using APK Signature Scheme v2: Size of APK Signing 
> > Block is not a multiple of 4096: 4128]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## 解决办法：
> > ### 1.降到Gradle3.2.1 打包后正常安装
> > Gradle编译版本 3.2.1
> > Gradle版本：distributionUrl=https://services.gradle.org/distributions/gradle-5.4.1-all.zip
> > ### 2.打包后的apk对齐、签名处理
> > 需要下载 [walle-cli-all.jar](https://github.com/Meituan-Dianping/walle/issues/264)
> > 
> > * 先进行对齐操作 ：$ANDROID_HOME/build-tools/26.0.2/zipalign -v 4 打的包.apk 新的包.apk
> > * V2签名工具再次签名新的Apk：$ANDROID_HOME/build-tools/26.0.2/apksigner sign --ks xxx.jks 新的包.apk
> > * 用walle-cli-all.jar写入渠道信息：java -jar walle-cli-all.jar put -c (渠道名，如：xiaomi) 新的包.apk
> > * 显示下是否写入渠道成功：java -jar walle-cli-all.jar show 新的包_渠道名.apk
> > 
> > 降级Gradle只是能临时解决，长久来看还是希望能支持一下Gradle4.0.0~
> 
> 感谢您的反馈，请使用 v1.1.7 版本，已修复该问题

可以说下怎么解决的吗？gradle 哪里的配置吗？
