### ISSUE TITLE
生成渠道包之后，需要重新签名吗？

### ISSUE THREAD

**Issue by endachao** [Meituan-Dianping/walle#340]
我是使用 `android studio ` 的 `build > generate signed apk` 打包的，也选择了 v1 和 v2 签名，然后使用 `cli` 

```

walle-cli-all.jar put -c 1001  app-release.apk

```

生成了渠道包，使用 `show` 也能显示出渠道信息，但是华为 `android 10` 安装不了，提示未包含证书，我又使用了 

```
apksigner sign 
```

重新签了名，才能安装，这个流程是正常的吗？因为我都没要看到需要重新签名的文档

**Comment by snailflying** [comment]
同样发现这个问题。华为手机安装出现异常。提示“未包含证书”

**Comment by endachao** [comment]
已放弃
