### ISSUE TITLE
有哪位大佬帮忙打个1.1.7的walle-cli 的jar包

### ISSUE THREAD

**Issue by TotoroLeon** [Meituan-Dianping/walle#347]

**Comment by 1290846731** [comment]
[Uploading walle-cli-all.jar.zip…]()

**Comment by 1290846731** [comment]
[walle-cli-all.jar.zip](https://github.com/Meituan-Dianping/walle/files/5303002/walle-cli-all.jar.zip)

**Comment by TotoroLeon** [comment]
> [walle-cli-all.jar.zip](https://github.com/Meituan-Dianping/walle/files/5303002/walle-cli-all.jar.zip)

3q!!

**Comment by szuwest** [comment]
为啥官方不在Release提供一下呢 @meituan
