### ISSUE TITLE
Could not find method walle()

### ISSUE THREAD

**Issue by midiao** [Meituan-Dianping/walle#35]
我根据文档配置后，Sync项目后，报下面的错误：
Error:(239, 0) Could not find method walle() for arguments [build_8e710nlujanxx3jeuass6znpr$_run_closure3@76a8173f] on project ':app' of type org.gradle.api.Project.
我已经加上apply plugin: 'walle'了。
希望能解答一下，谢谢~

**Comment by achellies** [comment]
现在应该好了吧，再重新编译一次试试

**Comment by midiao** [comment]
现在可以了，谢啦~
