### ISSUE TITLE
360加固后，使用walle.jar写入渠道后，无法安装，求助

### ISSUE THREAD

**Issue by xia-weiyang** [Meituan-Dianping/walle#351]
walle.jar是最新版本 1.1.6
360加固也是最新版 3.2.2.4

**Comment by gaoxuefeng** [comment]
你这个是不是加固后没有签名导致的,加固后需要重新签名

**Comment by TokenYc** [comment]
+1，偶尔会出现这种情况。

**Comment by nemo-ex** [comment]
重新编译解决
[https://github.com/jiangmw/walle/releases/tag/v1.1.8](https://github.com/jiangmw/walle/releases/tag/v1.1.8)
