### ISSUE TITLE
使用360加固签名之后无法添加渠道信息

### ISSUE THREAD

**Issue by AlphaBoom** [Meituan-Dianping/walle#4]
![image](https://cloud.githubusercontent.com/assets/11323557/21884939/6d0ab800-d8f0-11e6-8f9d-c267bc61e82a.png)

**Comment by achellies** [comment]
360加固不支持V2签名吧，可以先找个v2签名的APK加固后在Android 7.0上是否能够成功安装

**Comment by AlphaBoom** [comment]
不使用360辅助工具的签名   直接使用apksigner 签名之后可以写入了
