### ISSUE TITLE
gradle assembleRelease 生成多渠道包，最好设计成可选。

### ISSUE THREAD

**Issue by ihrthk** [Meituan-Dianping/walle#41]

**Comment by achellies** [comment]
详细说一下吧，没明白意思

**Comment by ihrthk** [comment]
现在 执行 gradle assembleRelease 一定会生成多渠道包，有时不需要生成多渠道包，只是执行正常的构建过程。希望把是否生成渠道包，设计成可选。

**Comment by achellies** [comment]
可以在build.gradle中walle的闭包配置注释掉，如果需要打渠道包时把注释去掉就行了

**Comment by achellies** [comment]
擦，又点成close and comment了，这个需求我们可以后面讨论下是否支持上

**Comment by achellies** [comment]
已经加上了，通过assemble${variantName}Channels来输出多渠道包，而正常构建的assemble${variantName}不打渠道包，会在 V1.0.5版本中发布
