### ISSUE TITLE
多渠道附加信息的需求

### ISSUE THREAD

**Issue by peerless2012** [Meituan-Dianping/walle#48]
有这么个需求，App内部会有评价这个功能，跳转到应用市场评价，并且需要优先跳转到所发渠道的应用商城。

例如：当前发版的渠道是360，但是手机上如果装了360和应用宝则直接跳转到360，而不是让用户去选择。如果手机上没有渠道对应的应用市场，则让用户选择或者提示未安装市场。

因为每个渠道的附加信息是不一样的，所以建议在渠道里面可以配置每个渠道的附加信息，并且也可以配置全局的公用的附加信息。

channel文件中可能类似下面的：

```
#360渠道
360cn:package=com.qihoo.appstore,arg1=xxx
#应用宝渠道
myapp:package=com.tencent.android.qqdownloader,arg1=xxx
```

或者

```
#360渠道
360cn package:com.qihoo.appstore,arg1:xxx
#应用宝渠道
myapp package:com.tencent.android.qqdownloader,arg1:xxx
```

@achellies

**Comment by achellies** [comment]
其实就是想让每个频道有自己特殊的一个信息呗，目前只支持写入不同的channel，其他额外的信息是各渠道共用的，是否可以用channel来做你上面的需求呢？

**Comment by achellies** [comment]
我们也考虑下是否有必要针对每个channel单独提供写入其他的特殊信息

**Comment by peerless2012** [comment]
确实，你说的方法也能实现目前的需求，channel中 `,` 、`.` 、`=`  、`:` 不会影响渠道的写入和读取吧？

**Comment by achellies** [comment]
> 确实，你说的方法也能实现目前的需求，channel中 , 、. 、= 、: 不会影响渠道的写入和读取吧？
 不会影响

**Comment by zhouaijia** [comment]
期待这个需求的实现..............

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/64#issuecomment-283879371
