### ISSUE TITLE
能给个demo吗?

### ISSUE THREAD

**Issue by xuekaiqi** [Meituan-Dianping/walle#49]
能给个gradle 配置demo吗？ 现在还没看懂怎么用！水平有限，希望能照顾下我们这样的猿友！

**Comment by achellies** [comment]
https://github.com/Meituan-Dianping/walle/tree/master/app  这个就是个demo，是在build.gradle的walle这个闭包中配置需要的参数， 通过assembleReleaseChannels就能打出渠道包，
