### ISSUE TITLE
proposal: 将 payload 标准化

### ISSUE THREAD

**Issue by magicdawn** [Meituan-Dianping/walle#5]
通过阅读代码发现, 是在 `APK_SIGNATURE_SCHEME_V2_BLOCK_ID = 0x7109871a;`
ID = `0x7109871a;` 处写了一个 json 字符串

```js
{
  "channel": "channel_name",
   ...extrainfo
}
```

这个 ID 也算 magic number, 这样 Reader 才能读到. 
标准化之后, 就不局限与打包了, 我需要读DB, 写 APK,  算MD5, 写DB, 上传 CDN 等等, 需要使用其他语言来写...

**Comment by achellies** [comment]
APK_SIGNATURE_SCHEME_V2_BLOCK_ID = 0x7109871a 这个id是V2签名的的ID，

我们的PayloadWriter本身提供 一个可以写入任意ID的函数

public static void put(final File apkFile, final int id, final ByteBuffer buffer)

**Comment by magicdawn** [comment]
哦说错了

这个
https://github.com/Meituan-Dianping/walle/blob/v1.0.0/payload_reader/src/main/java/com/meituan/android/walle/ApkUtil.java#L31

**Comment by achellies** [comment]
这个数值只有4个字节，不能作为魔数，会存在和APK（ZIP）里内容冲突的可能，
