### ISSUE TITLE
在应用使用了productFlavors之后，配置wall总会出现错误

### ISSUE THREAD

**Issue by memorycj** [Meituan-Dianping/walle#51]
Error:Plugin requires 'APK Signature Scheme v2 Enabled' for InnerTestProductFlavors.

v2SigningEnabled 已经配置

![image](https://cloud.githubusercontent.com/assets/16283516/23156328/67a877dc-f851-11e6-8ab3-40b15c1c9d25.png)

**Comment by GavinCT** [comment]
参考 https://github.com/Meituan-Dianping/walle/issues/20

**Comment by memorycj** [comment]
@GavinCT 我这边debug和release版本是有配置签名文件的..

**Comment by GavinCT** [comment]
你可以有选择的贴一下啊你的配置吧  不然没法帮你确认啥  肯定是你个人配置的问题

**Comment by huangyanan** [comment]
@memorycj 是否在gradle脚本中有三方工具，类似解压apk重新签名的这种步骤？
