### ISSUE TITLE
360加固后，重新打渠道问题

### ISSUE THREAD

**Issue by v7lin** [Meituan-Dianping/walle#53]
你好！
对于360开放平台的流氓式强制加固，后需要重新签名，重新打渠道问题，美团是怎么解决的呢？
我使用了“jarsigner -verbose -keystore ${KEYSTORE_PATH} -storepass ${STOREPASS} -signedjar ${SIGN_APK_PATH} -digestalg SHA1 -sigalg MD5withRSA ${APK_PATH} ${ALIAS_NAME} -tsa https://timestamp.geotrust.com/tsa”这个命令重新签名后（这个签名命令是旧版本的签名命令，找不到v2版的签名命令），使用 java -jar walle-cli-all.jar put -c qihu360 CloudReader-qihu360_signed.apk 打渠道，会直接抛异常。

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/21

**Comment by GavinCT** [comment]
后期会单独整理一个wiki  暂时先看下上面提供的相关issue吧

**Comment by wswenyue** [comment]
https://github.com/wswenyue/channelHelper

这是我写的一个基于walle命令行工具打包的脚本。支持360渠道
