### ISSUE TITLE
打单个渠道包会把所有的渠道包都打好了。。。

### ISSUE THREAD

**Issue by tianyajuechen** [Meituan-Dianping/walle#54]
#### 问题一
我执行这个命令 **./gradlew clean assembleReleaseChannels -PchannelList=meituan** 结果它顺带把我channel文件里的所有渠道包都打好了

**Comment by achellies** [comment]
这个问题应该是channelList和channelFile不是互斥的关系造成

**Comment by achellies** [comment]
问题已经修复，等新版本发布即可

**Comment by carl1990** [comment]
./gradlew clean assembleMeituanReleaseChannels   同样会生成所有渠道的包
