### ISSUE TITLE
productFlavors 配置 buildConfigField

### ISSUE THREAD

**Issue by zhangniuniu** [Meituan-Dianping/walle#57]
您好，我想问下，我根据不同的渠道，我们需要设置不同的属性，想下面这种怎么实现？
 productFlavors {
        dev {
            buildConfigField 'boolean', 'DIDA_FLAVOR', "true"
        }
      yingyongbao {
            buildConfigField 'boolean', 'DIDA_FLAVOR', "false"
        }
}

**Comment by GavinCT** [comment]
walle与这些并不冲突，可以继续使用啊

**Comment by achellies** [comment]
我猜是不是类似这种需求？ #48

**Comment by zhangniuniu** [comment]
@achellies 是的，类似这种，而且我们划分的有点多，现在gradle插件是还不支持这个功能是吗，只能拆分成几种基础包，然后分别对基础包进行walle是吗

**Comment by GavinCT** [comment]
1.1.0已经发布，支持为每个channel配置extraInfo
