### ISSUE TITLE
没有 assembleReleaseChannels 

### ISSUE THREAD

**Issue by imtianx** [Meituan-Dianping/walle#59]
在terminal 下进行多渠道打包时，提示没有 assembleReleaseChannels  task，是没有配置好么

**Comment by achellies** [comment]
这个提示是在我们的Demo里运行提示的吗？如果在自己的App中请先apply这个插件

**Comment by winnerliu** [comment]
Demo 上也提示 Task 'assembleReleaseChannels' not found in root project 'walle'.
是还需要配置哪里的呢

**Comment by ouyangpeng** [comment]
@winnerliu 

报了错误 Task 'assembleReleaseChannels' not found in root project 'App_MultiChannelBigData'.
错误如下所示：

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleReleaseChannels' not found in root project 'App_MultiChannelBigData'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

运行 assemble${variantName}Channels，如果没有flavor就是assembleDebugChannels,如果有Flavor就是assembleFlaverNameChannels

 注释掉了flavor 相关配置，然后使用命令 gradlew clean assembleReleaseChannels 不报错了。
