### ISSUE TITLE
360加固后的apk无法签名，有没有什么推荐工具

### ISSUE THREAD

**Issue by moonljt521** [Meituan-Dianping/walle#6]
360加固后的apk无法签名，不加固只自己混淆的安全性没那么高，如何解决这个问题，或者您有什么更优的方案

**Comment by GavinCT** [comment]
看下之前这个是否可以帮到你   
https://github.com/Meituan-Dianping/walle/issues/4

**Comment by heweimxcz** [comment]
@moonljt521  可以签名啊，为什么不能签，我签名玩之后在用walle注入渠道信息都成功了

**Comment by heweimxcz** [comment]
@GavinCT 解决问题的思路很犀利，关键还能一步一步的去寻找答案，我看你们复用了android提取magic块的那段代码，我的先去了解zip的相关知识估计才能明白

**Comment by hpu-spring87** [comment]
之前美团多渠道打包方案，在Android 7.0+应该也是可行的，只不过需要打包脚本改动一下，加过标识渠道的空文件后，重新用v2签名一下，打包效率跟之前没多大差别。可以看一下我写的一个打包小工具：
[https://github.com/hpu-spring87/MultiSignTools](https://github.com/hpu-spring87/MultiSignTools)

**Comment by GavinCT** [comment]
@hpu-spring87 每个apk都重新签名会加大耗时，当渠道包数量较大不推荐。 

ps:  图形化方案确实很赞。不过大部分公司可能会跟自己的ci环境结合，例如Jenkins。

注: 之前的多渠道方案如果强制使用v1签名在7.0也是可行的， 如果是v2必须重新签名

**Comment by GavinCT** [comment]
@moonljt521 是否解决了问题呢？ 看大部分人反馈是没有问题的，这里暂时先关闭issue了，如果还有问题可以再联系

**Comment by JinJieGu** [comment]
写了一个工具，专门修复类似360加固重签名和批量注入渠道，2秒搞定。支持全平台，有兴趣可以看下，
https://github.com/Jay-Goo/ProtectedApkResignerForWalle，@GavinCT 作者如果觉得还可以，希望能放到360加固失效方案里，帮助更多同学。

**Comment by JinJieGu** [comment]
写了一个工具，专门修复类似360加固重签名和批量注入渠道，2秒搞定。支持全平台，有兴趣可以看下，@GavinCT 作者如果觉得还可以，希望能放到360加固失效方案里，帮助更多同学。
https://github.com/Jay-Goo/ProtectedApkResignerForWalle

**Comment by GavinCT** [comment]
@JinJieGu 点个赞，我们看在wiki里收录一下

**Comment by NiLuogege** [comment]
对简单而且能有效解决问题的工具 https://github.com/NiLuogege/walleBuildChannel
