### ISSUE TITLE
walle-cli如何制定 新APK的Name

### ISSUE THREAD

**Issue by zhangniuniu** [Meituan-Dianping/walle#61]
指定渠道配置文件 java -jar walle-cli-all.jar batch -f /Users/Meituan/walle/app/channel  用这个命令进行批量打包，如何规范新的apk name

**Comment by GavinCT** [comment]
你想要规范的格式大概是什么样子呢？  和plugin相比 这时候很多参数已经不能直观的取到了

**Comment by GavinCT** [comment]
举个示例吧 我们改进也有个方向

**Comment by zhangniuniu** [comment]
@GavinCT 是有点麻烦，不适合所有的，我自己解决好了，谢谢哈
