### ISSUE TITLE
gradlew clean assembleReleaseChannels -PchannelFile=channel打包之后原先的BuildConfig不见

### ISSUE THREAD

**Issue by Yuphee** [Meituan-Dianping/walle#62]
为什么我运行指令打包后项目clean掉了，然后我项目中的BuildConfig变红找不到了

**Comment by achellies** [comment]
这个不应该啊，打渠道包盒build config不冲突，你clean下试试

**Comment by Yuphee** [comment]
不光是这个所有R文件也都找不到了，clean一下是会好的，但是打完包那么多红，看着不舒服
