### ISSUE TITLE
使用java -jar walle-cli.jar -h报NullPointerException错误

### ISSUE THREAD

**Issue by hyhe** [Meituan-Dianping/walle#63]
<pre>hyhedeMacBook-Air:ajkwalle hyhe$ java -jar walle-cli.jar -h
Exception in thread "main" java.lang.NullPointerException
	at com.beust.jcommander.JCommander.usage(JCommander.java:1134)
	at com.beust.jcommander.JCommander.usage(JCommander.java:1049)
	at com.beust.jcommander.JCommander.usage(JCommander.java:1041)
	at com.meituan.android.walle.WalleCommandLine.parse(WalleCommandLine.java:28)
	at com.meituan.android.walle.Main.main(Main.java:46)</pre>

因为我们公司的渠道命名规则是前缀加数字，如b00,b01，b999 这类有规则的命名方式，渠道号配置文件是b_00_999，所以对源码中WriteChannelsCommand.java类的parse方法做了修改
<pre>
      if (channelFile != null) {
            try {
                final List<String> lines = IOUtils.readLines(new FileInputStream(channelFile), "UTF-8");
                for (String line : lines) {
                    final String lineTrim = line.trim();
                    if (lineTrim.matches("^[a-zA-Z]_\\d*_\\d*")) {
                        String[] values = lineTrim.split("_");
                        String preStr = values[0];
                        int start = Integer.parseInt(values[1]);
                        int end = Integer.parseInt(values[2]);
                        for (int i = start; i <= end; i++) {
                            String channel = String.format("%s%s%d", preStr, i < 10 ? "0" : "",i);
                            generateChannelApk(inputFile, outputDir, channel);
                        }
                    } else {
                        continue;
                    }

                }
                System.out.println("finished!");
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
        }
</pre>
并且为了打“胖”jar包，在 build.gradle中jar中加了
<pre>
jar {
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    manifest {
        attributes 'Main-Class': 'com.meituan.android.walle.Main'
        attributes 'Walle-Version': VERSION_NAME
    }
}</pre>
见我的fork分支https://github.com/hyhe/walle
做了上述修改后，打出来的jar包 -h就报错了,其它命令参数可正常使用。

**Comment by GavinCT** [comment]
fat jar我引入了插件  打包的时候使用：
./gradlew :walle-cli:clean :walle-cli:shadowJar
这样再试试？

**Comment by hyhe** [comment]
解决了，跟打包没关系，原因是忘了为类AjkWriteChannelsCommand implements IWalleCommand 加@Parameters(commandDescription = "channel apk batch production")这句注解了，谢谢
