### ISSUE TITLE
 请问channelInfo.getExtraInfo()这个方法的数据如何写入

### ISSUE THREAD

**Issue by cocoas** [Meituan-Dianping/walle#64]
我想写在channel文件里，但是这样总是不对，可以说一下吗

**Comment by GavinCT** [comment]
extra目前在channel里还不支持 未来有计划 
现在只能通过plugin extraInfo  或者-PextraInfo为所有渠道统一插入

**Comment by cocoas** [comment]
plugin extraInfo 插入的话是也要弄一个channel文件这样还是怎么做呢？

**Comment by GavinCT** [comment]
看readme

**Comment by cocoas** [comment]
./gradlew clean assembleReleaseChannels -PchannelList=meituan -PextraInfo=buildtime:20161212,hash:xxxxxxx
你是说这句话吗，这个是要一个一个打包。不可以直接像一个channel文件一样弄一个extraInfo文件吗

**Comment by GavinCT** [comment]
![image](https://cloud.githubusercontent.com/assets/4016698/23540217/e866e630-001a-11e7-9e07-ed7b69886f71.png)
会给每个channel的apk加上相同的extraInfo

**Comment by GavinCT** [comment]
./gradlew clean assembleReleaseChannels -PchannelFile=channel -PextraInfo=buildtime:20161212,hash:xxxxxxx

也可以  不过都是所有channel 相同extraInfo    
不同channel不同extraInfo 有计划开发，暂时还没有提供

**Comment by cocoas** [comment]
知道了 非常感谢帮助

**Comment by GavinCT** [comment]
1.1.0已经发布，支持为每个channel配置extraInfo

**Comment by cocoas** [comment]
好勒  谢谢哥们儿
