### ISSUE TITLE
怎么分abi打包？

### ISSUE THREAD

**Issue by XiaoSeee** [Meituan-Dianping/walle#66]
如果我的配置里面写了
splits {
        abi {
            enable true
            reset()
            include 'armeabi', 'x86'
            universalApk false
        }
    }
每次打包出来都是x86的，怎么打出armeabi的？

**Comment by GavinCT** [comment]
与walle无关的问题请自行google

**Comment by XiaoSeee** [comment]
配置了这个会在build\outputs\apk\下面有两个apk
xxx-armeabi-release.apk
xxx-x86-release.apk

我估计walle去找xxx-x86-release.apk添加渠道信息了，能不能配置下去找指定的apk。

好像用walle-cli-all.jar可以自己用命令行实现，能在‘build.gradle’里面配置一步到位就好了。

**Comment by achellies** [comment]
代码已经提交了，等待新的发布版本吧
