### ISSUE TITLE
Error:Plugin requires 'APK Signature Scheme v2 Enabled' for release.

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [Meituan-Dianping/walle#68]
集成报错，我并没有设置V2为fase.

**Comment by achellies** [comment]
你的Gradle版本呢？提一些gradle中的配置吧？

**Comment by KevinOfNeu** [comment]
Same issue, gradle 2.14.1

**Comment by KevinOfNeu** [comment]
@AndroidJohnsonWang ref to [issue](https://github.com/Meituan-Dianping/walle/issues/20)

**Comment by missingbobo** [comment]
我同样遇到这种问题，对gradle版本有需求吗？如果有为什么文档没有标明

**Comment by KevinOfNeu** [comment]
@missingbobo 升级Gradle Plugin版本，大于2.2.0即可，如果手工设置了v2SigningEnabled＝false，需要去掉。请参考 #20
