### ISSUE TITLE
为什么一直在闪屏页进不去啊，可能是什么问题呢

### ISSUE THREAD

**Issue by ananas-xxj** [Meituan-Dianping/walle#7]

**Comment by achellies** [comment]
请提供更详细的日志呗

**Comment by ananas-xxj** [comment]
可是打不开软件，我应该提供什么日志信息呢？

**Comment by GavinCT** [comment]
Most software projects have a bug tracker of some kind. GitHub’s tracker is called Issues, and has its own section in every repository.

非walle问题请询问自己同事
