### ISSUE TITLE
关于walle-cli-all功能增强的建议

### ISSUE THREAD

**Issue by peerless2012** [Meituan-Dianping/walle#72]
在 #48 中，我提过每个渠道需要自己的附加信息的issue。

* 现在在插件中增加了对于Config的支持，但是有些情况下（比如 大数字的强制加固 要求），加固完后，还是需要手动走签名和写渠道，但是最新的walle-cli-all `v1.1.0` 没看到对于Config文件的支持。

    需要的命令可能类似于
    ```
    java -jar walle-cli-all.jar batch -f xxx\channel -ef xxx/config.json xxx.apk
    ```
* 还有一点，上面这个命令会以channel中的名字来命名文件，比如渠道是`360cn`,apk名称就是`xxx_360cn.apk`、`xxx_myapp.apk`,由于打出渠道包后是要给上线人员的，他们还需要根据这个字符串去找对应市场名，所以最好能指定生成的apk为`xxx_360.apk`、`xxx_应用宝.apk`这种。

**Comment by GavinCT** [comment]
1. walle-cli.jar会提供功能支持。 初步定在1.1.1的补丁版中修复。  目前如果有这种需求的话可以先写个shell脚本 每次执行 put -e -c这种指令暂时满足需求
2. config.json会考虑价格alias字段，如果有alias优先用alias替换channel显示，但alias只作为显示，不写入apk

**Comment by GavinCT** [comment]
注：alias功能可能不会支持channel文件了 我们让config.json具有这个功能吧

**Comment by GavinCT** [comment]
hi 
1.1.1已经发布， https://github.com/Meituan-Dianping/walle/tree/master/walle-cli    batch2指令可以满足你的需求了
