### ISSUE TITLE
关于多渠道打包之后，友盟统计的渠道包不能统计正常的渠道包的问题？

### ISSUE THREAD

**Issue by ouyangpeng** [Meituan-Dianping/walle#74]
不知道第二代稳不稳定啊？ 刚刚接到多渠道打包的需求，前段时间研究了一代，然后发现有个问题是接入的友盟SDK等，读取的渠道包是写死在AndroidManifest.xml中的 UMENG_CHANNEL 字段，不能去更改，因此打算用自己公司开发的大数据SDK，然后在代码中去读取美团方案弄出来的渠道包。
现在一看技术文档，发现第二代出来了，第二代和第一代应该是一样的，友盟等SDK无法自动识别多渠道打包后的渠道包名吧。 现在有两个疑问点：
1、不知道针对友盟SDK等写死在AndroidManifest.xml中配置有没有好的方案呢？
2、第二代多渠道打包，看提交日期是刚提交不久，不知道稳不稳定？

**Comment by ouyangpeng** [comment]
刚刚查看了友盟统计的开发文档，发现可以动态代码设置渠道名。介绍如下：

如果希望在代码中配置Appkey、Channel、Token（Dplus）等信息，请在程序入口处调用如下方法：

MobclickAgent. startWithConfigure(UMAnalyticsConfig config)

UMAnalyticsConfig初始化参数类，提供多参数构造方式：


UMAnalyticsConfig(Context context, String appkey, String channelId)

UMAnalyticsConfig(Context context, String appkey, String channelId, EScenarioType eType)

UMAnalyticsConfig(Context context, String appkey, String channelId, EScenarioType eType,Boolean isCrashEnable)

构造意义：
String appkey:官方申请的Appkey
String channel: 渠道号
EScenarioType eType: 场景模式，包含统计、游戏、统计盒子、游戏盒子
Boolean isCrashEnable: 可选初始化. 是否开启crash模式

**Comment by liuhea** [comment]
意思是，不使用AndroidManifest.xml的配置方式，将在UMAnalyticsConfig(Context context, String appkey,“channel”)? 还是需要在项目中集中walle sdk ,然后使用Walle动态获取渠道号的方法。

**Comment by liuhea** [comment]
![image](https://user-images.githubusercontent.com/19663285/27020460-321fbd30-4f74-11e7-9014-d6648684a3b1.png)

**Comment by GavinCT** [comment]
@liuhea  网络原因请自己排查

**Comment by GavinCT** [comment]
@liuhea  请尽量在自己的issue里提问 不要随意在他人的issue的评论  如果是想提问本issue的创建者除外
减少对他人的打扰~~

**Comment by dazeGitHub** [comment]
我知道怎么办了，我用的百度统计，这么办：
   String channel = WalleChannelReader.getChannel(this.getApplicationContext());//获取美团walle当前渠道
   StatService.setAppChannel(this, channel, true);//设置百度统计当前渠道
