### ISSUE TITLE
打一个渠道的包，为什么会把channel文件里的所有渠道的包都打出来？

### ISSUE THREAD

**Issue by sylviaMo** [Meituan-Dianping/walle#78]
命令是./gradlew clean assembleSunmiReleaseChannels

**Comment by achellies** [comment]
目前是这么设计的，我们想法是flavor和渠道包是解耦的，如果想打一个包，可以修改channelfile或者其它配置，只配置一个channel

**Comment by GavinCT** [comment]
打这种单个渠道包的场景应该就是测试一下吧？  很频繁？ 
我们在考虑之后觉得这种场景有限 所以就没有继续支持。 

如果只是临时测试，并不是频繁场景的话，可以考虑在当前工程下建个shell
```
// 打出一个apk
./gradlew clean assembleMeituanRelease
// 使用cli加上渠道
java -jar walle-cli-all.jar put -c meituan /Users/Meituan/Downloads/app.apk
```
