### ISSUE TITLE
已开启v2SigningEnabled 但总提示需要开启

### ISSUE THREAD

**Issue by missingbobo** [Meituan-Dianping/walle#79]
Error:Plugin requires 'APK Signature Scheme v2 Enabled' for 

我的配置如下
    signingConfigs{
        release {
            storeFile file("../sign_formal_key.key")
            storePassword "******"
            keyAlias ******
            keyPassword "******"
            v2SigningEnabled true
        }
        debug{
            storeFile file("../sign_formal_key.key")
            storePassword "******"
            keyAlias "******"
            keyPassword "******"
            v2SigningEnabled true
        }
    }

**Comment by achellies** [comment]
你的buildTypes里配置签名了吗？把buildTypes的贴一下

**Comment by achellies** [comment]
看看这个怎么解决的： #20
