### ISSUE TITLE
Jenkins Gradle 自动化编译之后，没有生成多渠道包？

### ISSUE THREAD

**Issue by ouyangpeng** [Meituan-Dianping/walle#81]
在Android Studio 中，安装demo的配置配置好我的项目之后，执行命令
```
./gradlew clean assembleReleaseChannels
```
之后，在build/outputs/channels目录下生成了我配置好的几十个多渠道版本的apk。但是当我将配置上传到服务器，并使用Jenkins自动化编译之后，并未生成相应的多渠道版本apk，只生成了一个默认的Release版本apk，不知道哪里出了问题，求大神帮忙！

Jenkins上的gradle编译配置为：
```
Invoke Gradle scrpt --> Use Gradle Wrapper --> Task -->clean assembleRelease --stacktrace
```

[](url)
![default](https://cloud.githubusercontent.com/assets/5885735/23749873/4114f9ae-0505-11e7-83d4-eb3fc184f8b5.png)

转移到FTP服务器配置为：
![default](https://cloud.githubusercontent.com/assets/5885735/23750188/b9e0fb48-0506-11e7-9039-7e10a675f0b2.png)

编译成功，转移到FTP服务器成功
![default](https://cloud.githubusercontent.com/assets/5885735/23750104/60e75df2-0506-11e7-9a3d-ca51d4e6de38.png)
但是FTP服务器就是没有编译出来的多渠道包
![default](https://cloud.githubusercontent.com/assets/5885735/23750152/9129bf6e-0506-11e7-875a-35566d193cd3.png)

**Comment by ouyangpeng** [comment]
[](url)
![default](https://cloud.githubusercontent.com/assets/5885735/23749873/4114f9ae-0505-11e7-83d4-eb3fc184f8b5.png)

**Comment by achellies** [comment]
通过assemble${flavorName}Channels来生成渠道吧，你在jenkins上配置的是assembleRelease，要配置 assembleReleaseChannels

**Comment by ouyangpeng** [comment]
@achellies 哎，尴尬，写的太快了，没注意。 把命令``` clean assembleReleaseChannels ``` 写错了成了```clean assembleRelease```，难怪只生成一个Release版本的apk。
改了之后，就生成了相应的多渠道包。 谢谢提醒！
![default](https://cloud.githubusercontent.com/assets/5885735/23779804/92fb3788-057d-11e7-9aa8-5a2273f6fae0.png)

![default](https://cloud.githubusercontent.com/assets/5885735/23779829/c01318b2-057d-11e7-82f3-5bbfd871497d.png)

**Comment by StephenGiant** [comment]
哥们还是细心点好

**Comment by ouyangpeng** [comment]
@StephenGiant 是啊 好尴尬的，写的太快了，忘记写完整的命令了。
