### ISSUE TITLE
Error:Plugin requires 'APK Signature Scheme v2 Enabled' for release.

### ISSUE THREAD

**Issue by maplebilly** [Meituan-Dianping/walle#83]
如题的错误如何解决，在build里已经配置 v2signature true  还是无效呀。
`signingConfigs{
        release{
            v2SigningEnabled true
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }`

**Comment by achellies** [comment]
signingConfigs{ release{ v2SigningEnabled true } }  这里面需要配置签名文件、密码等信息啊
