### ISSUE TITLE
为什么要下载gradle 3.3

### ISSUE THREAD

**Issue by ananas-xxj** [Meituan-Dianping/walle#85]
为什么要下载gradle 3.3

**Comment by GavinCT** [comment]
我们使用的时2.14.1 不会下载3.3  https://github.com/Meituan-Dianping/walle/blob/master/gradle/wrapper/gradle-wrapper.properties

请自行确定原因吧

**Comment by Reteyery** [comment]
我也遇到这个问题了，屡次下载3.3

**Comment by GavinCT** [comment]
自己点了升级project的plugin版本？  我们默认是2.14.1 没有使用3.3
如果你是最新的ide  会提示升级到最新的2.3的plugin 同时会把gradle版本也升级 ，
so 确认下自己操作

**Comment by ananas-xxj** [comment]
@Reteyery 嗯  我后面把gradle版本降到2.14.1打的包

**Comment by ananas-xxj** [comment]
@GavinCT 对我的gradle版本是3.3  它会提示正在下载gradle3.3  但是下不下来（那这么说我是不是用不了gradle3.3）

**Comment by GavinCT** [comment]
great fire wall @ananas-xxj

**Comment by ananas-xxj** [comment]
@GavinCT 好吧
