### ISSUE TITLE
Error:Plugin requires 'APK Signature Scheme v2 Enabled' for devRelease.

### ISSUE THREAD

**Issue by gdutkyle** [Meituan-Dianping/walle#90]
按照文档配置后，出现Error:Plugin requires 'APK Signature Scheme v2 Enabled' for devRelease.这个错误，请问怎么解决呢？

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/68 
https://github.com/Meituan-Dianping/walle/issues/83

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/20
