### ISSUE TITLE
v1.1.1 不支持打包参数传 channel 了？

### ISSUE THREAD

**Issue by hamberluo** [Meituan-Dianping/walle#91]

**Comment by GavinCT** [comment]
目前考虑到临时性打一两个包的需求不大 做了取消。
如果有需要可以描述下场景，我们再考虑下。

命令行 cli 还是支持传参的   plugin为了使用逻辑清晰暂时不再支持

**Comment by hamberluo** [comment]
临时性打包的需求很大啊，比如我们打一些推广的包

**Comment by GavinCT** [comment]
可以理解为临时性的推广包？   突然需要在某市场推广，然后你们checkout到当时的版本上，然后临时打个包出去？

**Comment by hamberluo** [comment]
是这样的

**Comment by GavinCT** [comment]
那其实你需要的时 -P这种临时生成一下的需求是吧

**Comment by hamberluo** [comment]
是的哈

**Comment by GavinCT** [comment]
好的  我们考虑下。 
目前的想法是恢复-Pchannel 这种，但是-P执行的时候忽略 channelFile 和 configFile这两项配置，保留format、output等配置项，应该也符合预期吧

**Comment by hamberluo** [comment]
是的，其实这个打包选项是给市场推广人员的，他们只要输入渠道名即可

**Comment by GavinCT** [comment]
不过其实是这样 如果存留了当时版本的apk的话 ，直接用cli处理一下即可。 其实是相同的，而且省去了打包时间，在美团其实是这样做的。
重新put channel会进行覆盖

**Comment by GavinCT** [comment]
只是个建议吧 其实是用cli更省时间 而且也挺方便 。  不过我们也考虑还原-P的能力吧

**Comment by hamberluo** [comment]
cli适用于只改channel的情况，我们推广的市场包可能会改圆形或者方形logo，闪屏图片等等

**Comment by GavinCT** [comment]
ok 明白了

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/releases/tag/v1.1.2  已经恢复-P能力

**Comment by hamberluo** [comment]
我看恢复的是-PChannelList，不是-PChannelFile啊

**Comment by GavinCT** [comment]
你是固定的包？
-PchannelFile这种固定的需求问什么不提前打好呢？
如果不是固定的 那channellist和 channelfile又有什么区别呢？

**Comment by GavinCT** [comment]
> 是的，其实这个打包选项是给市场推广人员的，他们只要输入渠道名即可

我看你当时提到的 channellist完全可以满足啊    channelFile用配置配就好了。
-P会有优先执行

**Comment by hamberluo** [comment]
channel file 并不是专门为了固定的包才使用。
对市场推广人员来说，他是不关心 channel file 的，只需要开发提供给他一个方式，比如以下方式
achannel bchannel cchannel ，以空格的形式分开。
对打包来讲，如果直接在P参数上做，不如 channel file 来得解耦。
这中间做得一层参数到 channel file 的转换方便维护。

**Comment by GavinCT** [comment]
@hamberluo 已经恢复-PchannelFile  并新增-PconfigFile

**Comment by hamberluo** [comment]
@GavinCT 感谢~

**Comment by GavinCT** [comment]
应该的  ^_^
