### ISSUE TITLE
怎么注入manifest中的第三方需要的渠道信息meta-data值

### ISSUE THREAD

**Issue by abcdqianlei1990** [Meituan-Dianping/walle#92]
我现在成功打包了，但是manifest中有好几个第三方需要的渠道信息统计的meta data，我该怎么设置这些值呢，之前是使用place holder ，flavor打包时候注入的。

比如下面的 CHANNEL,我打包meituan这个渠道的包，那么打包完后，我希望这个value也是meituan而不是default
<meta-data android:name = "CHANNEL" android:value="default"/>

**Comment by GavinCT** [comment]
https://github.com/Meituan-Dianping/walle/issues/74

**Comment by abcdqianlei1990** [comment]
我看过那个issue，但是并不适用，我用的那个第三方只能在manifest中写渠道信息

**Comment by GavinCT** [comment]
那你应该是第一次使用这种打包方式吧？   美团第一代的渠道包工具是否用过？

如果没有的话，目前看来是没法这样做了。这属于统计sdk的不完善吧，walle本身是依靠不写入代码区，不用重新打包来减少生成时间的。

**Comment by abcdqianlei1990** [comment]
我确实是第一次用walle，那这样看来是不适用了

**Comment by abcdqianlei1990** [comment]
最后和第三方咨询了，被告知其实是有设置渠道的方法，但是开发文档中没更新

**Comment by GavinCT** [comment]
ok  那可以愉快的使用了

**Comment by gaoleicoding** [comment]
> ok 那可以愉快的使用了

你好，该怎么使用呢，帮忙谢谢
