### ISSUE TITLE
fileSHA1 无效

### ISSUE THREAD

**Issue by chenzj-king** [Meituan-Dianping/walle#93]
配置了fileSHA1.但是貌似无效.所有打包出来的文件sha1都是一样的.而且自己校验一下.没有一个包是匹配的.
使用的是Android Studio2.3、Gradle 3.4.1  

    walle {
    // 指定渠道包的输出路径
    apkOutputFolder = new File("${project.buildDir}/outputs/channels");
    // 定制渠道包的APK的文件名称
    apkFileNameFormat = '${appName}-${channel}-${buildType}-v${versionName}-${versionCode}-${buildTime}-${fileSHA1}.apk';
    // 配置渠道文件列表，也可以通过channelList来配置
    channelFile = "app/channel";
}

**Comment by achellies** [comment]
这一个bug，sha1取的是打渠道包之前的sha1，应该修改下

**Comment by achellies** [comment]
目前代码已经修改，等待新版本发布吧

**Comment by GavinCT** [comment]
1.1.2已经发布
