### ISSUE TITLE
我就想问个问题，walle可以在gradle中获取版本号信息吗？

### ISSUE THREAD

**Issue by MQHuan** [Meituan-Dianping/walle#96]
我就想问个问题，walle可以在gradle中获取版本号信息吗？

**Comment by achellies** [comment]
可以获取啊

**Comment by achellies** [comment]
插件里可以获取

**Comment by achellies** [comment]
AndroidArtifactVariant里面有versionName、VersionCode

**Comment by MQHuan** [comment]
兄弟，我问得有点歧义，不好意思，我想在gradle中拿到渠道号。

能给个代码不？感谢

类似下面andriod自己的productFlavors可以在gradle中拿到渠道号的代码
def getCurrentFlavor() {
    Gradle gradle = getGradle()
    String  tskReqStr = gradle.getStartParameter().getTaskRequests().toString()

    Pattern pattern;

    if( tskReqStr.contains( "assemble" ) )
        pattern = Pattern.compile("assemble(\\w+)(Release|Debug)")
    else
        pattern = Pattern.compile("generate(\\w+)(Release|Debug)")

    Matcher matcher = pattern.matcher( tskReqStr )

    if( matcher.find() )
        return matcher.group(1).toLowerCase()
    else
    {
        println "NO MATCH FOUND"
        return "";
    }
}
