### ISSUE TITLE
Task 'assembleReleaseChannels' not found 

### ISSUE THREAD

**Issue by changmen** [Meituan-Dianping/walle#97]
执行 ./gradlew clean assembleReleaseChannels 报错，错误信息为 Task 'assembleReleaseChannels' not found

**Comment by achellies** [comment]
看你当前是否定义了flavor
运行命令： assemble${flavor}${buildType}Channels,

如果没有flavor则是assembleReleaseChannels
如果定义了flavor（例如meituan)则是assembleMeituanReleaseChannels

**Comment by yanxinmiao** [comment]
@achellies 
其中meituan 是flavor中定义的任意一个吗 ？

**Comment by GavinCT** [comment]
@yanxinmiao 你想基于哪个flavor做渠道包就用哪个啊
