### ISSUE TITLE
7.0系统下安装渠道包依然失败

### ISSUE THREAD

**Issue by taoranziwangji** [Meituan-Dianping/walle#99]
使用adb install命令安装时提示：Failed to install /Users/vdo/AndroidStudioProjects/family-android/Fans/app/build/outputs/channels/Fans_v4.1_华为.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl528870403.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]

**Comment by GavinCT** [comment]
v2 签名开启了？ 
签名配置了？

**Comment by FYSong** [comment]
我这边已经开启了，其他7.0以下系统正常安装，7.0+提示【INSTALL_FAILED_UPDATE_INCOMPATIBLE】
